In [1]:
# 쥬피터 노트북 셀 크기 설정 
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; font-weight:bold }</style>"))

# 경고 메세지 X
import warnings
warnings.filterwarnings(action='ignore')

C:\Users\pusan\AppData\Local\Temp\ipykernel_12080\365181345.py:2: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML


### Numpy 개요
- Numpy란? Numeric + Python = Numpy(넘파이, 늄파이)
- 수학 및 과학 연산을 위한 파이썬 패키지
- 관련 사이트 : http://www.numpy.org
- 리스트와의 차이점
    - 하나의 데이터형만 지원
    - np.array 함수를 활용하여 ndarray 배열을 생성함
    - 행렬 연산 가능

### Numpy 모듈 임포트
- import numpy as 별칭(np)

In [2]:
import numpy as np

### Numpy 버전 확인하기
- numpy(또는 별칭 np).version

In [6]:
np.__version__

'1.21.5'

In [7]:
# 전체 모듈에 지원되는 메서드랑 속성 확인
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',


### 넘파이 배열 만들기
- 넘파이 배열을 생성하는 방법들
    - 1) np.array(리스트)
    - 2) 초기화함수
    - 3) 외부파일
    
### 파이썬리스트(list) => 넘파이 배열화(numpy.ndarray)
- np.array(리스트)
- 리스트변수 생성후 np.array(리스트명)
- np.array([값1, 값2....])
- 리스트 형태는 실수, 정수, 문자 넘파이 배열 가능
- 넘파이배열명 = np.array(리스트)

In [9]:
mylist = [1, 2, 3, 4, 5]
type(mylist),mylist

(list, [1, 2, 3, 4, 5])

In [10]:
# 넘파이배열화
arr = np.array(mylist)
type(arr),arr

(numpy.ndarray, array([1, 2, 3, 4, 5]))

In [11]:
print(arr)

[1 2 3 4 5]


In [13]:
#  넘파이배열 + print()
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [15]:
# 실수형 넘파이 배열 생성
# [정수+실수형] => 실수형 넘파이 배열
# 데이타형을 혼합하지 않음 => 단일화
arr = np.array([0, 1 , 3.5, 100 ,-6.7])
arr

array([  0. ,   1. ,   3.5, 100. ,  -6.7])

In [17]:
# 리스트는 데이타형 혼합가능 
mylist = [0, 1, 3.5, 100, -6.7]
mylist

[0, 1, 3.5, 100, -6.7]

In [20]:
# 문자열형태의 넘파이 배열 생성 
# [문자열+정수+불형] => 문자열 넘파이 배열 
arr = np.array(['파이썬 판다스 넘파이 머신러닝', '자바', 'HTML', 100, True])
arr

array(['파이썬 판다스 넘파이 머신러닝', '자바', 'HTML', '100', 'True'], dtype='<U16')

### 넘파이 구조 확인하기
- 넘파이배열명.shape
- 1차원 넘파이 배열의 구조(형태) = (갯수,) = tuple 구조
- 2차원 넘파이 배열의 구조(형태) = (행수,열수) = tuple 구조
- (전체갯수,)   (해숭, 열수)   (행수, 열수, 면수)
- ndim 차원 => 정수형 
- size 전체길이 => 정수형

In [22]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
arr1.shape, arr1.ndim, arr1.size, len(arr1)

[1 2 3 4 5]


((5,), 1, 5, 5)

In [25]:
# 2차원 리스트 생성
# 리스트의 경우 구성 리스트의 길이가 틀려도 된다.
myList1 = [[1,2,3],[100,200],[1000]]
myList1

[[1, 2, 3], [100, 200], [1000]]

In [28]:
# 2차원 넘파이 배열 생성 - 길이가 서로 다른 경우
# 1차원
arr2 = np.array([[1,2,3],[100,200],[1000]])
print(arr2)
arr2.shape, arr2.ndim, arr2.size, len(arr2)

[list([1, 2, 3]) list([100, 200]) list([1000])]


((3,), 1, 3, 3)

In [32]:
# 2차원 넘파이 배열 생성 - 구성 요소의 길이가 서로 같은 경우
arr3 = np.array([[1,2,3],[100,200,300],[1000,2000,3000]])
print(arr3)
arr3.shape, arr3.ndim, arr3.size, len(arr3)

[[   1    2    3]
 [ 100  200  300]
 [1000 2000 3000]]


((3, 3), 2, 9, 3)

### 넘파이배열과 리스트의 차이점은?
```
- 리스트의 경우 데이형이 다중인 경우 => 데이타형이 그대로 유지
- 넘파이배열의 경우는 하나의 데이터형만 유지
    문자 > 실수 > 정수
    
- 리스트인 경우에는 2차원 이상일때 각 차원의 길이가 달라도 된다
- 넘파이 배열인 경우에는 2차원 이상일때 각 차원의 길이가 달라진다면 1차원으로 정의된다.

- 리스트 연산자는 +, * 만 존재 
- 2개 이상의 넘파이 배열간의 행렬 연산이 가능하다.

- 인덱싱
1차원은 인덱싱이 리스트와 넘파이배열이 동일 
2차원 이상의 리스트 인덱싱 : 리스트명[i][j]
2차원 이상의 넘파이배열 인덱싱 : 넘파이배열명[i][j], 넘파이배열명[i,j]
```

In [34]:
# 리스트 인덱싱 - 1차원
myList1 = [1,2,3,4,5]
myList1[0], myList1[-1]

(1, 5)

In [38]:
myList2 = [[1,2,3],[100,200],[1000]]
myList2[0], myList2[0][0], myList2[-1], myList2[-1][0]

([1, 2, 3], 1, [1000], 1000)

In [39]:
# 넘파이배열 인덱싱 - 1 차원
arr1 = np.array([1, 2, 3, 4, 5])
arr1[0], arr1[-1]

(1, 5)

In [41]:
# 넘파이배열 인덱싱 - 2 차원 
# 넘파이배열명[행인덱스][열인덱스]
# 넘파이배열명[행인덱스,열인덱스]
arr2 = np.array([ [1, 2, 3], [100, 200, 300], [1000, 2000, 3000] ])
print(arr2)
print()
arr2[0], arr2[0][0], arr2[-1], arr2[-1][0]

[[   1    2    3]
 [ 100  200  300]
 [1000 2000 3000]]



(array([1, 2, 3]), 1, array([1000, 2000, 3000]), 1000)

### 리스트 구조의 연산 테스트

In [43]:
list_a = [1,2,3,4,5]
list_b = [10,20,30,40,50]
# +는 연결의 의미 => 합집합
list_a+list_b

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [46]:
# TypeError
# list_a-list_b
# list_a*list_b

In [48]:
# 리스트*숫자 => 반복의 의미
list_a*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [51]:
# 리스트 구조에서 같은 위치의 값들을 연산하려면?
result = []
for i in range(len(list_a)):
    # 같은 위치의 인덱스끼리 연산
    temp = list_a[i] - list_b[i]
    result.append(temp)
result

[-9, -18, -27, -36, -45]

### 리스트 구조의 연산 테스트

In [53]:
# 1차원 넘파이 배열 생성
arr_a = np.array([1,2,3,4,5])
arr_b = np.array([10,20,30,40,50])
arr_a, arr_b

(array([1, 2, 3, 4, 5]), array([10, 20, 30, 40, 50]))

In [56]:
# 두 배열간의 연산자 적용
# 같은 인덱스 끼리 연산
arr_a - arr_b

array([ -9, -18, -27, -36, -45])

In [55]:
# 실수몫
arr_a / arr_b

array([0.1, 0.1, 0.1, 0.1, 0.1])

In [57]:
# 정수몫
arr_a // arr_b

array([0, 0, 0, 0, 0], dtype=int32)

### 넘파이 배열에 특정 숫자 곱하기
브로드캐스팅(Broadcasting) : 1차원 또는 2차원 배열 모두 각각 원소에 값이 합쳐진다

In [58]:
arr1 = np.array([1,2,3,4,5])
arr1*5

array([ 5, 10, 15, 20, 25])

In [59]:
arr2 = np.array([ [1, 2, 3], [100, 200, 300], [1000, 2000, 3000] ])
arr2

array([[   1,    2,    3],
       [ 100,  200,  300],
       [1000, 2000, 3000]])

In [61]:
arr2%2

array([[1, 0, 1],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

### 넘파이 초기화함수
- np.zeros(갯수) : 0으로 구성된 1차원 넘파이 배열
- np.zeros([행수,열수]) : 0으로 구성된 2차원 넘파이 배열
- np.ones(갯수) : 1로 구성된 1차원 넘파이 배열
- np.ones([행수,열수]) : 1로 구성된 2차원 넘파이 배열
- np.empty(갯수) : 1차원 비어있는 배열. 0과 비슷. 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있을 수 있다.
- np.empty([행수,열수]) : 2차원 비어있는 배열. 0과 비슷하지만 실수로 구성될 수 있음
- np.full(갯수, 초기값) : 모든 요소를 지정한 값으로 지정하는 1차원 넘파이 배열
- np.full([행수,열수], 초기값) : 모든 요소를 지정한 값으로 지정하는 2차원 넘파이 배열
- np.eye(갯수) : 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0일 정사각형인 2차원 넘파이 배열
- np.tri(갯수) : 주대각선을 기준으로 삼각형 형태의 1로 지정되는 정사각형 2차원 넘파이 배열
- np.?_like(넘파이배열명) : 지정된 넘파이배열과 shape 가 같은 넘파이 배열 생성
    -   np.zeros_like(넘파이배열명)
    -   np.ones_like(넘파이배열명)
    -   np.full_like(넘파이배열명, 값)
    -   np.empty_like(넘파이배열명)

In [66]:
# 1차원 넘파이 배열 길이 10인데 초기값은 모두 0 => 실수형 배열
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [65]:
# 초기값은 모두 0 => 정수형 배열 
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [85]:
# 2차원 넘파이 배열 3행3열 , 초기값은 모두 0 => 실수형 배열
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [71]:
# 2차원 넘파이 배열 3행3열 , 초기값은 모두 0 => 정수형 배열 
np.zeros([3,3],dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [83]:
# 2차원 넘파이 배열 3행3열 , 초기값은 모두 10 => 실수형 배열
np.ones([3,3],dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [80]:
# 2차원 넘파이 배열 3행3열 , 초기값은 모두 10. => 실수형 배열
np.full([3,3],10.)

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [86]:
np.empty([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [88]:
# 행과 열의 개수가 같다
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [89]:
# 행과 열의 개수가 같다
np.eye(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [92]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [93]:
np.tri(3, dtype=int)

array([[1, 0, 0],
       [1, 1, 0],
       [1, 1, 1]])

In [95]:
arr = np.array([[1,2,3],[4,5,6],[6,7,8]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [96]:
# arr과 같은 너파이 배열 구조인데 초기값은 0
np.zeros_like(arr)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [97]:
# arr 과 같은 넘파이 배열 구조인데 특정값으로 초기화  =>  실수형 
np.full_like(arr, 5.5, dtype=float)

array([[5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5]])

In [98]:
# arr과 같은 넘파이 배열 구조인데 기존 메모리에 적재되어 있는 값으로 출력
np.empty_like(arr)

array([[4128860, 6029375, 3801155],
       [5570652, 6619251, 7536754],
       [ -65536,      -1, 7208960]])

In [102]:
# 파이썬의 range() 함수 테스트
# range(start, end, step)
# start ~ end -1 : 자동숫자생성
range(10), type(range(10)), list(range(10))

(range(0, 10), range, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
# 1~100 사이에서 홀수만 리스트로 생성
print(list(range(1,101,2)))

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]


In [107]:
# 1~10까지 넘파이 배열 생성
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
# 10~1까지 넘파이 배열 생성
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [119]:
# for문 + 넘파이 배열
arr1 = np.arange(1,11)
print(arr1)
for item in arr1:
    print(item)
for i in range(len(arr1)):
    print(i,' = ', arr1[i])

[ 1  2  3  4  5  6  7  8  9 10]
1
2
3
4
5
6
7
8
9
10
0  =  1
1  =  2
2  =  3
3  =  4
4  =  5
5  =  6
6  =  7
7  =  8
8  =  9
9  =  10


In [121]:
# 0~10범위를 5등분
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [123]:
# -10~10범위를 5등분 => 정수형# 0~10범위를 5등분
np.linspace(0,10,5)
np.linspace(-10,10,5, dtype=int)

array([-10,  -5,   0,   5,  10])

### 넘파이배열의 데이터형 확인하기
- type(변수/값) => 전체객체의 자료형
- 넘파이배열.dtype : int32, <U2 , float64
- dtype : data type
- 넘파이배열생성시 자료형함께 지정하기
    - np.array(리스트, dtype=자료형)

### 리스트의 데이타형 확인

In [124]:
# 리스트 + type() 테스트 
myList = [1, 2, 3.14, True, '강아지']
type(myList), type(myList[0]), type(myList[2]), type(myList[3]), type(myList[-1])

(list, int, float, bool, str)

In [ ]:
# AttributeError
# myList[0].dtype

In [135]:
# # 넘파이배열 + type() + dtype 테스트 
# arr1 = np.array(([1, 2, 3])
# arr2 = np.array([1.3, 4.5, 4.56])
# arr3 = np.array(['파이썬', '자바', 'DB'])
# type(arr1),type(arr2),type(arr3)
# 넘파이배열 + type() + dtype 테스트 
arr1 = np.array([1, 2, 3])
arr2 = np.array([1.3, 4.5, 4.56])
arr3 = np.array(['파이썬프로그래밍', '자바', 'DB'])
type(arr1), type(arr2), type(arr3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [136]:
arr1.dtype, arr2.dtype, arr3.dtype

(dtype('int32'), dtype('float64'), dtype('<U8'))

In [137]:
print(type(arr1))

<class 'numpy.ndarray'>


# 넘파이 배열 생성시 자료형 설정

np.array(리스트, dtype=자료형)
자료형은? int, float, str, '<U숫자', bool

In [139]:
# 문자숫자로 구성된 넘파이 배열 생성 
arr1 = np.array([1, 2, 3, 4, 5], dtype=str)
arr1, arr1.dtype

(array(['1', '2', '3', '4', '5'], dtype='<U1'), dtype('<U1'))

In [144]:
# 논리형(불형 bool)으로 구성된 넘파이 배열 생성
# 0 은 False, 나머지 숫자 모두는 True
arr2 = np.array([1, 0,-11,0,5], dtype=bool)
arr2, arr2.dtype

(array([ True, False,  True, False,  True]), dtype('bool'))

### 데이터 형변환하기(캐스팅)
- 새배열변수 = 배열이름.astype(데이터형)
- 데이터형 : float, int, '<U2', np.str

### 자료형변환
- 자동형 => 정수 < 실수 < 문자열
- 강제형 -> 캐스팅(casting)

In [145]:
# 자동 형변환
# 정수 + 실수 + 문자열 + 논리 => 문자열
arr = np.array([1,3.14,'100',True])
arr, arr.dtype

(array(['1', '3.14', '100', 'True'], dtype='<U32'), dtype('<U32'))

In [147]:
# 캐스팅
# 배열이름.astype(데이터형)
arr1 = np.array([1, 2, 3])
arr2 = np.array([1.3, 4.5, 4.56])
arr3 = np.array(['100', '200', '300'])
arr1.dtype, arr2.dtype, arr3.dtype

(dtype('int32'), dtype('float64'), dtype('<U3'))

In [149]:
# 정수형 => 논리형 (원본X, 미리보기)
arr1.astype(bool)

array([ True,  True,  True])

In [150]:
# 정수형 => 논리형 (원본X, 미리보기)
arr1.astype(bool), arr1

(array([ True,  True,  True]), array([1, 2, 3]))

In [151]:
# 정수형 => 논리형 (원본X, 미리보기)
arr1.astype(bool), arr1

(array([ True,  True,  True]), array([1, 2, 3]))

In [152]:
# 원본도 함께 변경
arr1 = arr1.astype(bool)
arr1

array([ True,  True,  True])

In [152]:
# 원본도 함께 변경
arr1 = arr1.astype(bool)
arr1

array([ True,  True,  True])

In [153]:
# 실수형 => 정수형 
arr2, arr2.astype(int)

(array([1.3 , 4.5 , 4.56]), array([1, 4, 4]))

In [154]:
# 실수형 => 정수형 
# 소숫점 이하는 무조건 잘림 => 값의 손실
arr2, arr2.astype(int)

(array([1.3 , 4.5 , 4.56]), array([1, 4, 4]))

In [155]:
# 문자열 => 실수형 
arr3, arr3.astype(float)

(array(['100', '200', '300'], dtype='<U3'), array([100., 200., 300.]))

In [157]:
arr4 = np.array(['100', '200', '300', '3.14'])
# 문자열 => 정수형 
# ValueError
# arr4.astype(int)

# 문자열 => 실수형 
arr4.astype(float)

array([100.  , 200.  , 300.  ,   3.14])

In [158]:
# 문자열 => 실수형 => 정수형 
arr4.astype(float).astype(int)

array([100, 200, 300,   3])

### Numpy 배열의 구조 변경
- 1차원 => 2차원 / 2차원=>1차원
- 넘파이배열명.reshape(행수,열수) : 1차원=>2차원, 2차원=>2차원
- 넘파이배열명.flatten() : 2차원 => 1차원
- 넘파이배열명.reshape(-1,?) : 전체요소(size)기준. 2차원. size를기반으로 row 개수 선정

### 1차원(5) => 2차원(5행1열)

In [162]:
# 1~9 1차원 배열 생성
arr = np.arange(1,10)
arr, arr.ndim, arr.shape

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), 1, (9,))

In [161]:
# 1차원 => 2차원
arr_a = arr.reshape(3,3)
arr_a, arr_a.ndim, arr_a.shape

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 2,
 (3, 3))

In [163]:
# 1차원 => 2차원
arr_b = arr.reshape(1,9)
arr_b, arr_b.ndim, arr_b.shape

(array([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), 2, (1, 9))

In [165]:
# 2차원 => 1차원
# 1~10 사이의 숫자로 구성된 넘파이 배열, 2행 5열
arr2 = np.arange(1,11).reshape(2,5)
arr2, arr2.ndim, arr2.shape

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 2,
 (2, 5))

In [173]:
arr2.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [176]:
arr3 = arr2.reshape(-1)
arr3, arr3.ndim, arr3.shape

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), 1, (10,))

In [178]:
# 2차원 => 2차원 구조 변경
# 넘파이배열명.reshape(-1,?) : 전체요소(size)기준. 2차원. size를기반으로 row 개수 선정
arr2, arr2.ndim, arr2.shape

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 2,
 (2, 5))

In [182]:
# 5행 2열
arr2.reshape(5,2)
arr2.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

### Numpy 배열의 크기 변경
- 배열의 모양만 변경된다.
- 넘파이배열명.resize(행수,열수, refcheck=False)
- 배열 크기 증가시 남은 공간은 0으로 채워진다.
- 배열의 크기 감소시 포함되지 않은 값은 삭제된다.
- 원본에 바로적용

In [192]:
# 100~600 구성된 넘파이 배열 생성 => 2행 3열
# arr1 = np.arange(100,601,100).reshape(2,3)
arr1 = np.array([[100, 200, 300],
       [400, 500, 600]])
arr1

array([[100, 200, 300],
       [400, 500, 600]])

In [185]:
# 2행 3열 => 3행 3열
# ValueError
# arr1.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [194]:
arr1.resize(3,3, refcheck=False)
arr1

array([[100, 200, 300],
       [400, 500, 600],
       [  0,   0,   0]])

In [198]:
# 2행 3열 => 2행 2열
arr2 = np.array([[100, 200, 300],[400, 500, 600]])
print(arr2)
arr2.resize(2,2)
arr2

[[100 200 300]
 [400 500 600]]


array([[100, 200],
       [300, 400]])

### Numpy 배열의 축 변경
- 넘파이배열명.T
- T는 Transpose. 행과 열이 서로 변경된다.
- 넘파이배열명.swapaxes(축1,축2)

In [203]:
# 2행 5열
arr = np.arange(11,21).reshape(2,5)
arr, arr.shape

(array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]),
 (2, 5))

In [204]:
# 5행 2열
arr.T, arr.T.shape

(array([[11, 16],
        [12, 17],
        [13, 18],
        [14, 19],
        [15, 20]]),
 (5, 2))

In [206]:
arr.swapaxes(0,1)

array([[11, 16],
       [12, 17],
       [13, 18],
       [14, 19],
       [15, 20]])

In [207]:
print(arr)
arr.swapaxes(0,1)

[[11 12 13 14 15]
 [16 17 18 19 20]]


array([[11, 16],
       [12, 17],
       [13, 18],
       [14, 19],
       [15, 20]])

In [208]:
print(arr)
arr.swapaxes(1,0)

[[11 12 13 14 15]
 [16 17 18 19 20]]


array([[11, 16],
       [12, 17],
       [13, 18],
       [14, 19],
       [15, 20]])

### 1차원인 경우
-  넘파이배열이름[start:end]
-  넘파이배열이름[start:]
-  넘파이배열이름[:end]
-  넘파이배열이름[:]
-  넘파이배열이름[start:end:step]
-  넘파이배열이름[start::step]
-  넘파이배열이름[:end:step]
-  넘파이배열이름[::]

### 2차원인 경우
-  넘파이배열이름[start1:end1, start2:end2]
-  넘파이배열이름[start1:, start2:]
-  넘파이배열이름[:,:] = 넘파이배열이름[::,::] 
-  넘파이배열이름[start1:end1:step1, start2:end2:step2]
-  넘파이배열이름[start1::step1, start2::step2]

In [209]:
# 4행 5열의 넘파이 배열 생성 
arr = np.arange(1,21).reshape(4, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [210]:
# 1행만 출력
arr[::]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [211]:
arr[0,:]

array([1, 2, 3, 4, 5])

In [212]:
# 1열만 출력
arr[:,0]

array([ 1,  6, 11, 16])

In [213]:
# 마지막 열만 출력
arr[:,-1]

array([ 5, 10, 15, 20])

In [215]:
# 홀수번째 행만 출력 => 1,3행
arr[::2,::]
# arr[::2,:]
# arr[::2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [216]:
# 짝수번째 행만 출력 => 1,3행
arr[1::2,::]
# arr[1::2,:]
# arr[1::2]

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])

In [220]:
# 홀수번째 열만 출력 => 1,3,5열
arr[::,::2]
# arr[:,::2]

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15],
       [16, 18, 20]])

In [221]:
# 짝수번째 열만 출력 => 2,4열
arr[::,1::2]
# arr[:,1::2]

array([[ 2,  4],
       [ 7,  9],
       [12, 14],
       [17, 19]])

In [222]:
# 1~2행 범위에서 1~2열 범위만
arr[:2,:2]

array([[1, 2],
       [6, 7]])

In [223]:
# 3~4행 범위에서 2~4열 범위만
arr[2:,1:4]

array([[12, 13, 14],
       [17, 18, 19]])

In [224]:
# 홀수번째 행에서 홀수번째 컬럼만
arr[::2,::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

In [225]:
# 짝수번째 행에서 짝수번째 컬럼만
arr[1::2,1::2]

array([[ 7,  9],
       [17, 19]])

In [226]:
# 3행 3열의 값만 출력
arr[2,2], arr[2][2]

(13, 13)

### Numpy 배열의 값 교체하기
- 넘파이배열명[index] = 값
- 넘파이배열명[rowIndex][columnIndex] = 값

In [232]:
# 1차원 넘파이 배열 테스트
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [233]:
arr[0] = 1000
arr

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [234]:
# 2차원 넘파이 배열 테스트
arr2 = np.arange(10).reshape(5,2)
arr2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [238]:
# 마지막행 마지막열의 값을 교체
# arr2[-1][-1] = -999
arr2[-1,-1] = -999
arr2

array([[   0,    1],
       [   2,    3],
       [   4,    5],
       [   6,    7],
       [   8, -999]])

In [242]:
# 2행을 모두 100으로 교체
arr2[1] = 100
arr2

array([[   0,    1],
       [ 100,  100],
       [   4,    5],
       [   6,    7],
       [   8, -999]])

In [245]:
# 3~4에서 2열만 999로 교체
arr2[2:4,1] = 999
arr2

array([[  77,    1],
       [  77,  100],
       [  77,  999],
       [  77,  999],
       [  77, -999]])

### Numpy 배열의 값 삽입하기
- np.insert(배열명, 인덱스, 값) : 1차원 배열의 특정 위치에 값 삽입
- np.insert(배열명, 인덱스, 값, axis=0/1) : 2차원 배열의 특정 위치에 값 삽입
- 축(axis)를 지정하지 않으면 1차원 배열로 반환
- 추가할 방향을 axis로 지정
- 원본 배열 변경없이 새로운 배열 반환

In [247]:
# 1차원 넘파이배열 테스트
arr1 = np.zeros(5)
arr1

array([0., 0., 0., 0., 0.])

In [249]:
# 첫번째 위치에 100 삽입 => 원본 배열에 반영
arr1 = np.insert(arr1,0,100)
arr1

array([100.,   0.,   0.,   0.,   0.,   0.])

In [253]:
# 끝에서 2번째 위치에 -999 삽입
arr1 = np.insert(arr1,-1,-999)
arr1

array([ 100.,    0.,    0.,    0.,    0.,  100.,  100., -999.,    0.])

In [254]:
# 마지막 위치에 -999 삽입
arr1 = np.insert(arr1,len(arr1),-999)
arr1

array([ 100.,    0.,    0.,    0.,    0.,  100.,  100., -999.,    0.,
       -999.])

In [261]:
# 2차원 넘파이 배열 테스트
arr2 = np.arange(10).reshape(5,2)
arr2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [256]:
# axes 속성이 없는 경우 => 1차원 변경 => 특정 위치에 값 삽입
np.insert(arr2, 0 ,[100, 200])

array([100, 200,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [257]:
# 첫번째 행으로 삽입
np.insert(arr2, 0 ,[100, 200], axis=0)

array([[100, 200],
       [  0,   1],
       [  2,   3],
       [  4,   5],
       [  6,   7],
       [  8,   9]])

In [258]:
# 끝에서 2번째에 삽입
np.insert(arr2, -1 ,[-999, -999], axis=0)

array([[   0,    1],
       [   2,    3],
       [   4,    5],
       [   6,    7],
       [-999, -999],
       [   8,    9]])

In [264]:
# 마지막 행으로 삽입
print(arr2.shape, '행의 길이는? ', arr2.shape[0],'열의 길이는? ', arr2.shape[1])
np.insert(arr2, arr2.shape[0] ,[-999, -999], axis=0)

(5, 2) 행의 길이는?  5 열의 길이는?  2


array([[   0,    1],
       [   2,    3],
       [   4,    5],
       [   6,    7],
       [   8,    9],
       [-999, -999]])

In [265]:
# 1열로 삽입
np.insert(arr2, 0 ,[-1, -2, -3, -4, -5], axis=1)

array([[-1,  0,  1],
       [-2,  2,  3],
       [-3,  4,  5],
       [-4,  6,  7],
       [-5,  8,  9]])

In [267]:
# 마지막 열로 삽입
np.insert(arr2, arr2.shape[1] ,[-1, -2, -3, -4, -5], axis=1)

array([[ 0,  1, -1],
       [ 2,  3, -2],
       [ 4,  5, -3],
       [ 6,  7, -4],
       [ 8,  9, -5]])

### Numpy 배열의 값 삭제하기
- np.delete(배열명, 인덱스) : 1차원 배열에서 인덱스에 해당하는 값 삭제
- np.delete(배열명, 인덱스, axis=0/1) : 2차원 배열에서 인덱스에 해당하는 값 삭제.
- 축(axis)를 지정하지 않으면 1차원 배열로 반환
- 삭제할 방향을 axis로 지정
- 원본 배열 변경없이 새로운 배열 반환

In [269]:
# 1차원 삭제 테스트
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [271]:
# 첫번째 요소 삭제
np.delete(arr1, 0)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [273]:
# 마지막 요소 삭제
np.delete(arr1, -1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [275]:
# 2차원 삭제 테스트
arr2 = np.arange(1,21).reshape(4,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [277]:
# 2차원에서 축을 지정하지 않는다면?
# 1차원으로 변경된 후 해당 인덱스가 삭제
np.delete(arr2,0)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [279]:
# axis=0 축지정
# 첫열 삭제
np.delete(arr2,0,axis=0)

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [278]:
# axis=1 축지정
# 첫행 삭제
np.delete(arr2,0,axis=1)

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

### 얕은 복사(Shallow Copy) 와 깊은 복사(Deep Copy)
- 얕은 복사 : 객체를 새로운 객체로 복사하지만 원본 객체의 주소값을 복사. 원본이 변경되면 함께 변경
- 깊은 복사 : 전체 복사로 참조값의 복사가 아닌 참조된 객체 자체를 복사. 원본과 별개

In [284]:
# 파이썬 변수 복사
x = 100
# y는 x의 복사 변수
y = x
print(x,y)
# id() 주소번지 반환
print(id(x), id(y))

# 복사본의 값을 교체한다면?
y = 300
# 원본 불변 => 깊은 복사
print(x,y)
print(id(x), id(y))

100 100
2001329542608 2001329542608
100 300
2001329542608 1999341808272


In [289]:
# 파이썬의 리스트 => 얕은 복사
list_a = [1,2,3,4,5]
# list_b는 list_a의 복사본
list_b = list_a
print(id(list_a), id(list_b))
print(list_a, list_b)
print()

# 복사본 리스트의 특정 값 변경
# 원본 리스트에도 반영

list_b[0] = 100
print(id(list_a), id(list_b))
print(list_a, list_b)

1999340557056 1999340557056
[1, 2, 3, 4, 5] [1, 2, 3, 4, 5]

1999340557056 1999340557056
[100, 2, 3, 4, 5] [100, 2, 3, 4, 5]


In [302]:
# 파이썬의 리스트 => 깊은 복사 스타일로 변경하려면?
# 리스트명.copy()
list_a=[1,2,3,4,5]
list_c=list_a.copy()
print(id(list_a), id(list_c))
print(list_a, list_c)
print()

# 복사본 리스트의 특정 값 변경
# 원본 리스트에도 반영

list_c[0] = 100
print(id(list_a), id(list_c))
print(list_a, list_c)

1999339735104 1999317756352
[1, 2, 3, 4, 5] [1, 2, 3, 4, 5]

1999339735104 1999317756352
[1, 2, 3, 4, 5] [100, 2, 3, 4, 5]


In [336]:
# 넘파이배열 => 얕은 복사
arr_a = np.array([1,2,0,0])
arr_b = arr_a
# 깊은 복사 방식으로 복제본 생성 => copy() 매서드 필요
arr_c = arr_a.copy()
print(id(arr_a), id(arr_b), id(arr_c))
print(arr_a, arr_b, arr_c)

# 복사본 배열 값 변경 => 원본 배열에도 반영
arr_b[-1] = 777
arr_c[0] = 100
print(id(arr_a), id(arr_b), id(arr_c))
print(arr_a, arr_b, arr_c)

1999327107856 1999327107856 1999337064560
[1 2 0 0] [1 2 0 0] [1 2 0 0]
1999327107856 1999327107856 1999337064560
[  1   2   0 777] [  1   2   0 777] [100   2   0   0]


### 리스트의 슬라이싱 테스트

In [344]:
myList=[1,2,3,4,5]
# 리스트의 일부를 새로운 리스트로 생성
myList_sub = myList[:3]
print(myList, myList_sub)
print(id(myList), id(myList_sub))

# 복사본 값 변경후?
myList_sub[0] = -777
print(myList, myList_sub)
print(id(myList), id(myList_sub))

[1, 2, 3, 4, 5] [1, 2, 3]
1999311177024 1999318240448
[1, 2, 3, 4, 5] [-777, 2, 3]
1999311177024 1999318240448


### 넘파이배열의 슬라이싱 테스트

In [347]:
myArr=np.array([1,2,3,4,5])
# 일부를 새로운 넘파이배열로 생성 => 얕은 복사
# 주소번지는 서로 별개
myArr_sub = myArr[:3]
print(myArr, myArr_sub)
print(id(myArr), id(myArr_sub))

# 복사본 값 변경후?
myArr_sub[0] = -777
print(myArr, myArr_sub)
print(id(myArr), id(myArr_sub))

[1 2 3 4 5] [1 2 3]
1999337577136 1999337575696
[-777    2    3    4    5] [-777    2    3]
1999337577136 1999337575696


In [4]:
a=np.arange(6).reshape(2,3)

In [3]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [6]:
b=a>4

In [7]:
a[b]

array([5])