In [1]:
# 쥬피터 노트북 셀 크기 설정 
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; font-weight:bold }</style>"))

# 경고 메세지 X
import warnings
warnings.filterwarnings(action='ignore')

C:\Users\pusan\AppData\Local\Temp\ipykernel_17304\365181345.py:2: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML


### Numpy 모듈 임포트

In [2]:
import numpy as np

### 일반난수 : random 모듈
- 내장모듈 임포트 : import random
- random.random() : 0 부터 1 사이의 부동소수점(float) 숫자를 리턴한다
- random.randint(최소, 최대) : 입력 파라미터인 최소부터 최대까지 중 임의의 정수를 리턴한다
- random.randrange(시작,끝[,간격]) : 입력 파라미터인 시작부터 끝값까지 (지정된 간격으로 나열된) 숫자 중 임의의 정수를 리턴한다
- random.uniform(최소, 최대) : 입력 파라미터인 최소부터 최대까지 중 임의의 부동소수점(float) 숫자를 리턴한다

### random 모듈 임포트

In [3]:
import random

In [18]:
# 실수형 데이타
# random.random() - 0~1사이
print(random.random())
print(random.random())
print(random.random())

0.5921010894577713
0.5905675966900633
0.021471465360924147


In [66]:
# 실수형 데이타 2
# random.uniform(최소, 최대) - 최소~최대 사이
# -5~5 사이 숫자 10개를 리스트로 저장 (소수점 2자리까지만)
result_list = []
for i in range(10):
    result_list.append(round(random.uniform(-5,5),2))
print(result_list)
# print(random.uniform(-5,5))
# print(random.uniform(1,10))
# print(random.uniform(1,10))

[-0.89, -2.72, 1.21, -2.89, 4.83, 3.71, 1.77, -1.94, -3.45, -2.37]


In [71]:
# 정수형 데이타
# random.randint(최소, 최대)
result_list = []
for i in range(30):
    result_list.append(random.randint(1,100))
print(result_list)

[72, 85, 40, 99, 64, 87, 85, 36, 90, 94, 48, 35, 80, 85, 36, 58, 3, 61, 57, 41, 5, 44, 48, 21, 86, 31, 52, 78, 22, 36]


In [93]:
# 정수형 데이타 2
# random.randrange(시작, 끝, 간격)
# 1~100 사이 숫자중에서 홀수만 10개 생성
result_list = []
for i in range(10):
    result_list.append(random.randrange(1,100, 2))
print(result_list)

[23, 55, 59, 95, 83, 45, 65, 85, 3, 9]


In [107]:
# 리스트에 뽑기 1
# random.choice(리스트) : 1개만 출력
student_list = ['영희', '철수', '지원', '수영', '지훈']
print(f'오늘의 청소당번은? {random.choice(student_list)}')
print(f'내일의 청소당번은? {random.choice(student_list)}')

오늘의 청소당번은? 지원
내일의 청소당번은? 수영


In [111]:
# 리스트에 뽑기 2
# random.sample(리스트, n) : n개만 출력
print(f'오늘의 청소당번은? {random.sample(student_list,2)}')
print(f'내일의 청소당번은? {random.sample(student_list,2)}')

오늘의 청소당번은? ['영희', '철수']
내일의 청소당번은? ['철수', '수영']


In [137]:
# 리스트 섞기
# random.shuffle(리스트) => 원본 리스트에 바로 반영
student_list = ['영희', '철수', '지원', '수영', '지훈']
print(student_list)
random.shuffle(student_list)
print(student_list)
print(f'오늘의 청소당번은? {student_list[0]}, {student_list[-1]}')

['영희', '철수', '지원', '수영', '지훈']
['지원', '철수', '영희', '지훈', '수영']
오늘의 청소당번은? 지원, 수영


#### 퀴즈
- 로또 번호 뽑기 (1~45 숫자중에서 6개를 뽑아 로또 리스트를 생성한다.) 
- 조건 - 로또 번호는 중복값이 없어야 한다. 넘파이 배열이어야한다 
- 예시 로또 번호 [36 10 43 15 16 25]

In [148]:
num_list = list(range(1,46))
print(num_list)
lotto_list = random.sample(num_list, 6)
print(f'이번주 로또번호는? {lotto_list}')

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45]
이번주 로또번호는? [44, 19, 3, 11, 42, 27]


### Numpy 배열의 난수

In [9]:
# 실수형 넘파이 배열 생성
# np.random.randn(n)
# np.random.randn(row, column)

# 1차원
arr = np.random.rand(10)
print(arr, arr.ndim, arr.shape, arr.dtype)

[0.14374706 0.90289245 0.54766001 0.86352045 0.8798326  0.27502691
 0.37324322 0.03410481 0.80875488 0.66444279] 1 (10,) float64


In [8]:
# 2차원
arr = np.random.rand(5,3)
print(arr, arr.ndim, arr.shape, arr.dtype)

[[0.39194489 0.67376716 0.77697919]
 [0.66845152 0.07016164 0.71333275]
 [0.68533575 0.13184838 0.55326314]
 [0.10678376 0.86009682 0.71259822]
 [0.0556145  0.2084844  0.73303956]] 2 (5, 3) float64


In [17]:
# 실수형 넘파이 배열 생성 2
# np.random.uniform(최소, 최대,데이터수)
# np.random.uniform(최소, 최대, (행수,열수))

# 2차원 -10~10 사이 실수 3행 3열
arr = np.random.uniform(-10, 10, (3,3))
print(arr, arr.ndim, arr.shape, arr.dtype)

[[-3.7577017   2.21579911 -0.32169648]
 [-7.60298529  5.00396882 -1.56801217]
 [ 7.31575519  2.6811432   8.44338494]] 2 (3, 3) float64


In [19]:
np.random.randint?

In [30]:
# 정수형 넘파이 배열
# np.random.randint(start,end,size=갯수)
# np.random.randint(start,end,size=(행수,열수))

# 2차원
arr = np.random.randint(-100, 100, (5, 5))
print(arr, arr.ndim, arr.shape, arr.dtype)

[[-42 -67  -6  12  78]
 [-62 -97  94  28 -11]
 [ 71  52 -25  88  -3]
 [-68 -22 -13  51 -89]
 [ -4  55 -18  44   4]] 2 (5, 5) int32


In [31]:
arr = np.random.randint(-100, 100, 10)
print(arr, arr.ndim, arr.shape, arr.dtype)

[-44 -47 -90 -81   5 -66  68  77 -42  82] 1 (10,) int32


### np.random.choice()
- 리스트에서 무작위로 n개의 데이터를 추출할 때 사용한다.
- np.random.choice(데이타형은숫자/리스트, size=샘플숫자, replace=True/False, p=리스트)
- 데이타형이 리스트이면 데이터, 정수이면 arange(a) 명령으로 데이터를 생성한다.
- size : 정수. 샘플 숫자
- replace : 불리언. True이면 한번 선택한 데이터를 다시 선택 가능하다. 중복허용
- p : 리스트형태. 각 데이터가 선택될 수 있는 확률로 소숫점 단위로 지정. 합은 1이어야한다

In [79]:
# 리스트에서 뽑기 => 넘파이배열
# np.random.choice(데이타형은숫자/리스트, size=샘플숫자, replace=True/False, p=리스트)
# p는 확률
event_list = ['꽝', '스타버스 상품권 10만원', '라면 한상자', '오징어땅콩', '순금 30돈']
for i in range(10):
    item = np.random. choice(event_list, size=1, p=[0.7, 0.03, 0.06, 0.2, 0.01])
    print(f'당첨 상품은? {item}')

당첨 상품은? ['꽝']
당첨 상품은? ['오징어땅콩']
당첨 상품은? ['꽝']
당첨 상품은? ['꽝']
당첨 상품은? ['꽝']
당첨 상품은? ['꽝']
당첨 상품은? ['꽝']
당첨 상품은? ['꽝']
당첨 상품은? ['꽝']
당첨 상품은? ['꽝']


In [80]:
# 섞기 => 넘파이배열
# np.random.shuffle(리스트)
arr = np.arange(1,11)
print(arr)
np.random.shuffle(arr)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]
[ 3  8  2  6  5 10  1  4  9  7]


### np.random.seed()
- 한번 발생한 난수를 다시 표시할 때 사용
- np.random.seed(0~양수)

### 순서
- np.seed(숫자) # 시드설정 = 난수발생 1
- 난수발생 
- np.seed(숫자) # 설정된 시드의 난수 
- 난수발생

In [99]:
np.random.rand(3)

array([0.0680984 , 0.13103736, 0.71155109])

In [100]:
# 시드 설정
np.random.seed(10)
# 무작위 실수 생성
np.random.rand(3)

array([0.77132064, 0.02075195, 0.63364823])

In [105]:
# 시드를 호출하지 않은 경우
np.random.rand(3)

array([0.19806286, 0.76053071, 0.16911084])

In [109]:
# 시드 호출 후 다시 랜덤계열 함수 호출 
# 값이 같은지 확은 
np.random.seed(10)
np.random.rand(3)

array([0.77132064, 0.02075195, 0.63364823])

In [110]:
# 넘파이 배열에서 지원되는 함수 확인
# print(dir(np))

## Numpy 배열의 수학 함수 이용하기
### 제곱근과 로그 구하기
- np.sqrt(배열명) : 제곱근 구하기
- np.log10(배열명) : 로그 구하기

In [113]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [114]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [115]:
np.log10(arr)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])

In [116]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [117]:
np.log2(arr)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809])

In [118]:
# 원주율 
np.pi

3.141592653589793

In [119]:
# 자연상수 
np.e

2.718281828459045

### 삼각 함수(Trigonometrical Function)
- np.sin(배열 또는 리스트)
- np.cos(배열 또는 리스트)
- np.tan(배열 또는 리스트)

In [120]:
np.sin([10, 20, 90])

array([-0.54402111,  0.91294525,  0.89399666])

### 최댓값과 최솟값 출력하기
- 같은 배열에서 큰수나 작은수 출력 (최댓값, 최솟값)
- 조건은 넘파이배열형태의 숫자 자료형만 가능
    - np.max(배열), np.max(배열, axis=0/1)
    - np.min(배열), np.min(배열, axis=0/1) 
    - np.maximum(배열1, 배열2)
    - np.minimum(배열1, 배열2)

In [130]:
# 1차원 테스트 => 최댓값, 최솟값
# 1~100 사이에서 10개만 샘플 데이타 생성
arr = np.random.randint(1, 100, 10)
print(arr)
print(np.max(arr), np.min(arr))

[41 90 74 38  1 19 24  4 30 17]
90 1


In [133]:
# 2차원 테스트 => 최댓값, 최솟값
# 1~100 사이에서 25개만 샘플 데이타 생성 => 5행, 5열 구조
arr = np.random.randint(1, 100, (5,5))
print(arr)
print(np.max(arr), np.min(arr))

[[39 23 97 67 68]
 [63 96 28 83 63]
 [78 49 94 76 87]
 [38 12 22 34 96]
 [44 89 97 74 41]]
97 12


In [146]:
# np.min(배열), np.min(배열, axis=0/1)
print('컬럼의 최대값 => ', np.max(arr, axis=0))
print('행의 최대값 => ', np.max(arr, axis=1))

컬럼의 최대값 =>  [78 96 97 83 96]
행의 최대값 =>  [97 96 94 96 97]


In [147]:
# axis 속성을 지원하지 않는다면? 최댓값과 최솟값으로 반환
print('컬럼의 최대값 => ', np.max(arr))
print('행의 최대값 => ', np.min(arr))

컬럼의 최대값 =>  97
행의 최대값 =>  12


### 서로 다른 배열간의 최댓값과 최솟값
- np.maximum(배열1, 배열2)
- np.minimum(배열1, 배열2)

In [152]:
arr1 = np.random.randint(1, 100, 5)
arr2 = np.random.randint(1, 100, 5)
print(arr1)
print(arr2)

[29 40 92 10  8]
[23 33  4 10 53]


In [154]:
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))

[29 40 92 10 53]
[23 33  4 10  8]


### 배열 원소 전체의 합과 평균 구하기

- 배열이름.sum(axis=0)/배열이름.mean(axis=0) : 컬럼의 합과 평균
- 배열이름.sum(axis=1)/배열이름.mean(axis=1) : 행의 합과 평균

In [157]:
# 리스트의 합계와 평균은?
myList = [1,100,55]
sum(myList), sum(myList)/len(myList)

(156, 52.0)

In [164]:
# 1차원 배열의 합과 평균
arr = np.random.randint(1, 100, 10)
print(arr)
print(arr.sum(), arr.mean())
print(np.sum(arr), np.mean(arr))

[76 40 59 82 40 50 98 12 79 80]
616 61.6
616 61.6


In [188]:
# 2차원 배열의 합과 평균
arr = np.random.randint(1, 100, (5,5))
print(arr)
print('컬럼 기준 =>',arr.sum(axis=0), arr.mean(axis=0))
print('컬럼 기준 =>',np.sum(arr, axis=0), np.mean(arr, axis=0))
print('행 기준 =>',arr.sum(axis=1), arr.mean(axis=1))
print('행 기준 =>',np.sum(arr, axis=1), np.mean(arr, axis=1))

[[98 65 67  9 78]
 [55 22 66 85 57]
 [32 40 43 34 15]
 [77 25 86 82 49]
 [10 29 35 77 74]]
컬럼 기준 => [272 181 297 287 273] [54.4 36.2 59.4 57.4 54.6]
컬럼 기준 => [272 181 297 287 273] [54.4 36.2 59.4 57.4 54.6]
행 기준 => [317 285 164 319 225] [63.4 57.  32.8 63.8 45. ]
행 기준 => [317 285 164 319 225] [63.4 57.  32.8 63.8 45. ]


### 배열의 최대값/최소값의 인덱스
- np.argmax(넘파이배열) : 1차원 최대값 인덱스
- np.argmin(넘파이배열) : 1차원 최소값 인덱스
- np.argmax(넘파이배열, axis=0) : 2차원 최대값 인덱스
- np.argmin(넘파이배열, axis=1) : 2차원 최소값 인덱스

In [193]:
# 1차원 테스트
arr = np.random.randint(1,100,10)
print(arr)
print(f'최댓값은? {np.max(arr)} 최댓값의 인덱스는? {np.argmax(arr)}')

[ 3 74 36 82 37 29 48 20  3 65]
최댓값은? 82 최댓값의 인덱스는? 3


In [205]:
# 2차원 테스트 => 최댓값, 최솟값
# 1~100 사이에서 25개만 샘플 데이타 생성 => 5행, 5열 구조
arr = np.random.randint(1, 100, (5,5))
print(arr)
print('각 컬럼의 최댓값은?',np.max(arr, axis=0))
print('각 컬럼의 최댓값 인덱스 반환',np.argmax(arr, axis=0))

[[90 79 79 53 67]
 [51 27 21 31 45]
 [55 60 72 48 65]
 [45 70 14  2 84]
 [73 99 54 69 86]]
각 컬럼의 최댓값은? [90 99 79 69 86]
각 컬럼의 최댓값 인덱스 반환 [0 4 0 4 4]


### 중앙값
- np.median(넘파이배열명)

In [208]:
# 1차원에서 중앙값 확인 
arr = np.random.randint(1, 100, 9)
print(arr)
print('평균 =',np.mean(arr))
print('중앙값 =',np.median(arr))

[17 37 70 50 83 65 22 83 35]
평균 = 51.333333333333336
중앙값 = 50.0


In [209]:
np.sort(arr)

array([17, 22, 35, 37, 50, 65, 70, 83, 83])

In [217]:
# 리스트의 정렬
# 리스트명. sort()
# 원본에 바로 적용
myList = [12, 55, 66, 199, -90]
print(myList)
myList.sort()
print(myList)
print(myList.sort())

[12, 55, 66, 199, -90]
[-90, 12, 55, 66, 199]
None


### 정렬과 관련된 함수 이용하기
- np.sort(배열1차) / 배열명.sort() : 오름차순
- np.sort(배열1차)[::-1] : 내림차순
- np.sort(배열2차, axis=0/1)
    - np.sort(배열이름, axis=0) – 열방향으로 정렬하기
    - np.sort(배열이름, axis=1) – 행방향으로 정렬하기
    - np.flip(배열, axis=0 ) => 역순 뒤집기
- np.argsort(배열2차, axis=0/1) - 정렬시 인덱스 위치값 표시

In [231]:
# 1차원에서 중앙값 확인 
arr = np.random.randint(1, 100, 10)
print(arr)
print('오름차순으로 정렬 :',np.sort(arr))
print('내림차순으로 정렬 :',np.sort(arr)[::-1])
print('내림차순으로 정렬 :',np.flip(np.sort(arr)))

[38 64 99 64 14 30 47 69 20 98]
오름차순으로 정렬 : [14 20 30 38 47 64 64 69 98 99]
내림차순으로 정렬 : [99 98 69 64 64 47 38 30 20 14]
내림차순으로 정렬 : [99 98 69 64 64 47 38 30 20 14]


In [234]:
# 2차원 배열의 합과 평균
arr = np.random.randint(1, 100, (5,5))
print(arr)
print('컬럼 기준 =>',arr.sum(axis=0), arr.mean(axis=0))
print('행 기준 오름차순으로 정렬 : \n', np.sort(arr, axis=1))
print('컬럼 기준 오름차순으로 정렬 : \n', np.sort(arr, axis=0))
print('행 기준 오름차순으로 정렬 : \n', np.sort(arr, axis=1))

[[14 40  5 26  1]
 [95 56 84 56  4]
 [51 37 85 36 62]
 [50 24 96 50 38]
 [54 71 58 47 26]]
컬럼 기준 => [264 228 328 215 131] [52.8 45.6 65.6 43.  26.2]
행 기준 오름차순으로 정렬 : 
 [[ 1  5 14 26 40]
 [ 4 56 56 84 95]
 [36 37 51 62 85]
 [24 38 50 50 96]
 [26 47 54 58 71]]
컬럼 기준 오름차순으로 정렬 : 
 [[14 24  5 26  1]
 [50 37 58 36  4]
 [51 40 84 47 26]
 [54 56 85 50 38]
 [95 71 96 56 62]]
행 기준 오름차순으로 정렬 : 
 [[ 1  5 14 26 40]
 [ 4 56 56 84 95]
 [36 37 51 62 85]
 [24 38 50 50 96]
 [26 47 54 58 71]]


In [236]:
# 정렬시 인덱스 위치값 표시
# np.argsort(배열2차, axis=0/1)

In [237]:
# 1차원 테스트 
arr = np.random.randint(1, 100, size=10)
print(arr) 
print('오름차순으로 정렬 : ', np.sort(arr))
np.argsort(arr)

[34 72 10 34  7 33 32 35 91 92]
오름차순으로 정렬 :  [ 7 10 32 33 34 34 35 72 91 92]


array([4, 2, 6, 5, 0, 3, 7, 1, 8, 9], dtype=int64)

In [238]:
# 2차원  테스트 
# 1~100 사이에서 25개만 샘플 데이타 생성 => 5행 5열 구조 
arr = np.random.randint(1, 100, size=(5,5))
print(arr) 
print()
print('컬럼 기준 오름차순으로 정렬 : \n', np.sort(arr, axis=0))
np.argsort(arr, axis=0)

[[ 3 87 73 22 29]
 [82 28 40 34 50]
 [98 94 19 22 76]
 [ 2 41 95 51  6]
 [76 41 74 94 84]]

컬럼 기준 오름차순으로 정렬 : 
 [[ 2 28 19 22  6]
 [ 3 41 40 22 29]
 [76 41 73 34 50]
 [82 87 74 51 76]
 [98 94 95 94 84]]


array([[3, 1, 2, 0, 3],
       [0, 3, 1, 2, 0],
       [4, 4, 0, 1, 1],
       [1, 0, 4, 3, 2],
       [2, 2, 3, 4, 4]], dtype=int64)

## 배열 합치기 

```
np.vstack((배열1, 배열2)) : 행으로 합치기
np.hstack((배열1, 배열2)) : 열로 합치기
np.concatenate((배열1, 배열2, axis=1/0))
np.append(배열1, 배열2, axis=1/0)
```

In [239]:
arr_1 = np.arange(1, 6)
arr_2 = np.arange(11, 16)
arr_1, arr_2

(array([1, 2, 3, 4, 5]), array([11, 12, 13, 14, 15]))

In [242]:
# 행으로 합치기
# 1차원 + 1차원 => 2차원(2,5)
arr_3 = np.vstack((arr_1, arr_2))
arr_3, arr_3.ndim, arr_3.shape

(array([[ 1,  2,  3,  4,  5],
        [11, 12, 13, 14, 15]]),
 2,
 (2, 5))

In [241]:
# 열로 합치기 
# 1차원 (5,) + 1차원 (5,) => 1차원 (10,)
arr_4 = np.hstack((arr_1, arr_2))
arr_4, arr_4.ndim, arr_4.shape

(array([ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15]), 1, (10,))

In [243]:
# 2차원 배열로 합치기 테스트 
arr_1 = np.arange(1, 7).reshape(2,3)
arr_2 = np.arange(11, 17).reshape(2,3)
print(arr_1)
print()
print(arr_2)

[[1 2 3]
 [4 5 6]]

[[11 12 13]
 [14 15 16]]


In [245]:
# 행으로 합치기 
# 2차원 (2,3) + 2차원 (2,3) => 2차원(4, 3)
arr_3 = np.vstack((arr_1, arr_2))
arr_3, arr_3.ndim, arr_3.shape

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [11, 12, 13],
        [14, 15, 16]]),
 2,
 (4, 3))

In [246]:
# 열로 합치기 
# 2차원 (2,3) + 2차원 (2,3) => 2차원(2,6)
arr_4 = np.hstack((arr_1, arr_2))
arr_4, arr_4.ndim, arr_4.shape

(array([[ 1,  2,  3, 11, 12, 13],
        [ 4,  5,  6, 14, 15, 16]]),
 2,
 (2, 6))

In [248]:
# concatenate()를 이용한 넘파이 배열 합치기
# np.concatenate((배열1, 배열2), axis=1/0))
# np.concatenate([배열1, 배열2], axis=1/0))
# 1차원
arr_1 = np.arange(1, 6)
arr_2 = np.arange(11, 16)
arr_1, arr_2

(array([1, 2, 3, 4, 5]), array([11, 12, 13, 14, 15]))

In [249]:
np.concatenate((arr_1, arr_2), axis=0)

array([ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15])

In [252]:
# np.concatenate((arr_1, arr_2), axis=1)
# 1차원 + 1차원 != 2차원
#A xisError: axis 1 is out of bounds for array of dimension 1

In [255]:
# 2차원 배열로 합치기 테스트 
arr_1 = np.arange(1, 7).reshape(2,3)
arr_2 = np.arange(11, 17).reshape(2,3)
print(arr_1)
print()
print(arr_2)
np.concatenate((arr_1, arr_2), axis=1)

[[1 2 3]
 [4 5 6]]

[[11 12 13]
 [14 15 16]]


array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

### 리스트의 append(), insert()

In [260]:
myList = list(range(1,6))
myList

[1, 2, 3, 4, 5]

In [261]:
print(myList.append(100))
print(myList)

None
[1, 2, 3, 4, 5, 100]


In [263]:
# 첫밴째 위치에 값 삽입
myList.insert(0,-999)
myList

[-999, 1, 2, 3, 4, 5, 100]

In [264]:
# 마지막 위치에 값 삽입 
myList.insert(len(myList), -999)
myList

[-999, 1, 2, 3, 4, 5, 100, -999]

### 넘파이의 append(), insert()

In [283]:
arr = np.arange(1,6)
arr

array([1, 2, 3, 4, 5])

In [284]:
# insert()릴 이용한 값 추가
np.insert(arr,0, 100)

array([100,   1,   2,   3,   4,   5])

In [285]:
# 원본 배열에 적용
arr = np.insert(arr,0, 100)
arr

array([100,   1,   2,   3,   4,   5])

In [286]:
# 마지막 위치에 값을 추가해서 배열에 적용
arr = np.insert(arr, len(arr), 100)
arr

array([100,   1,   2,   3,   4,   5, 100])

In [287]:
# append()를 이용한 값 추가
# np.append(배열명, 값)
arr = np.append(arr, -88)
arr

array([100,   1,   2,   3,   4,   5, 100, -88])

In [289]:
# np.append(배열명, [값1, 값2 ....])
arr = np.append(arr, [100, 200, 300])
arr

array([100,   1,   2,   3,   4,   5, 100, -88, 100, 200, 300])

In [291]:
# 서로 다른 1차원 배열 합치기 - append() 활용
arr_1 = np.arange(1, 6)
arr_2 = np.arange(11, 16)
arr_3 = np.append(arr_1, arr_2)
# arr_3 = np.append(arr_1, arr_2, axis=0)
arr_3

array([ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15])

In [ ]:
# AxisError: axis 1 is out of bounds for array of dimension 1
# 1차원 + 1차원 != 2차원
# np.append(arr_1, arr_2, axis=1)

In [294]:
# 2차원 배열로 합치기 테스트 - append() 활용 
arr_1 = np.arange(1, 7).reshape(2,3)
arr_2 = np.arange(11, 17).reshape(2,3)
print(arr_1)
print()
print(arr_2)
arr_3 = np.append(arr_1, arr_2, axis=0)
print()
print(arr_3)
arr_4 = np.append(arr_1, arr_2, axis=1)
print()
print(arr_4)
# 2차원 + 2차원 인데 축 지정을 하지 않는다면? => 1차원
arr_5 = np.append(arr_1, arr_2)
print()
print(arr_5)

[[1 2 3]
 [4 5 6]]

[[11 12 13]
 [14 15 16]]

[[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [14 15 16]]

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]]

[ 1  2  3  4  5  6 11 12 13 14 15 16]


### 배열 분할 

```
배열명1, 배열명2 ... = np.split(분할배열명, [v1, v2 ...]) : 특정값을 기준으로 배열 분할
배열명1, 배열명2 ... = np.vsplit(분할배열명, [index]) : 수직 분할, 1차원으로 분할. 인덱스는 0 제외
배열명1, 배열명2 ... = np.hsplit(분할배열명, [index]) : 배열 분할, 2차원으로 분할. 인덱스는 0 제외
```

In [299]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [300]:
# 2개의 배열로 분할 - 0~4, 5~9
np.split(arr, [5])

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [303]:
# 파이썬의 변수값 할당
x, y, z = 100, 200, 300
print(x)
print(y)
print(z)


100
200
300


In [305]:
# 2개의 배열로 분할한 후 각 배열로 할당  
arr_a, arr_b = np.split(arr, [5])
print(arr)
print(arr_a)
print(arr_b)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]


In [306]:
# 4개의 배열로 분할한 후 각 배열로 할당  
arr_a, arr_b, arr_c, arr_d = np.split(arr, [2, 5, 8])
print(arr)
print(arr_a)
print(arr_b)
print(arr_c)
print(arr_d)

[0 1 2 3 4 5 6 7 8 9]
[0 1]
[2 3 4]
[5 6 7]
[8 9]


In [307]:
# 2차원 테스트
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [309]:
# np.vsplit(분할배열명, [index])
arr_a, arr_b = np.vsplit(arr, [1])
print(arr)
print()
print(arr_a)
print()
print(arr_b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]]

[[4 5 6]
 [7 8 9]]


In [310]:
# np.hsplit(분할배열명, [index])
arr_a, arr_b = np.hsplit(arr, [1])
print(arr)
print()
print(arr_a)
print()
print(arr_b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1]
 [4]
 [7]]

[[2 3]
 [5 6]
 [8 9]]


In [312]:
# np.hsplit(분할배열명, [index])
arr_a, arr_b, arr_c = np.hsplit(arr, [1, 2])
print(arr)
print()
print(arr_a)
print()
print(arr_b)
print()
print(arr_c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1]
 [4]
 [7]]

[[2]
 [5]
 [8]]

[[3]
 [6]
 [9]]


### 중복값 제거하기
- set(리스트) 
- np.unique(넘파배열명)

In [317]:
# 중복값이 있는 리스트
myList = [1, 2, 3, 4, 5, 6, 5, 8, 8]
print(myList, len(myList))

# 집합 구조로 변경 : 리스트 => 집합 => 리스트
myList2 = list(set(myList))
print(myList2, len(myList2))

[1, 2, 3, 4, 5, 6, 5, 8, 8] 9
[1, 2, 3, 4, 5, 6, 8] 7


In [316]:
# 넘파이배열의 중복값 제거
arr = np.array([1, 2, 3, 4, 5, 6, 5, 8, 8])
print(arr, len(arr))

# 중복값 제거
arr2 = np.unique(arr)
print(arr2, len(arr2))

[1 2 3 4 5 6 5 8 8] 9
[1 2 3 4 5 6 8] 7


In [318]:
# 1차원 테스트
arr = np.random.randint(-100, 100, 10)
arr

array([-91, -89,  59,  57, -97,  52,  14,  12,  47, -97])

### 비교와 논리 연산

In [325]:
# 1차원 테스트 
arr = np.random.randint(-100, 100, 10)
arr

array([ 87,  18, -50,  37,  57,  61, -51,   7,  63, -81])

In [326]:
# 음수일 경우 False, 양수이거나 0인 경우 True
arr >= 0

array([ True,  True, False,  True,  True,  True, False,  True,  True,
       False])

In [329]:
# 2차원 테스트 
# arr = np.random.randint(-100, 100, 9).reshape(3,3)
arr = np.random.randint(-100, 100,(3,3))
arr

array([[ 50, -29,  80],
       [-75, -20, -61],
       [-79,  52,  21]])

In [330]:
# 음수일 경우 False, 양수이거나 0인 경우 True
arr >= 0

array([[ True, False,  True],
       [False, False, False],
       [False,  True,  True]])

### All & Any
- 넘파이배열을 이용한 조건식 => True/False 배열수만큼 리턴
- np.all(조건식) => 모든 값이 조건식에 만족 => True (And)
- np.any(조건식) => 값 중 하나만 만족 => True (Or)

In [339]:
arr = np.array([-76, -93, -17, -59, 81])

# 배열 중 양수가 하나라도 존재한는가?
print(arr > 0)
print(np.any(arr > 0))
# 배열 값은 모두 음수인가?
print(arr < 0)
print(np.all(arr < 0))

[False False False False  True]
True
[ True  True  True  True False]
False


In [340]:
# 2차원 테스트 - 모두 음수
arr = np.array([[-81, -37, -21], [-63, -97, -5]])
arr

array([[-81, -37, -21],
       [-63, -97,  -5]])

In [346]:
# 배열 값은 모두 음수인가?
print()
print(arr < 0)
print(np.all(arr < 0))
print()
# 배열 중 양수가 하나라도 존재한는가?
print(arr > 0)
print(np.any(arr > 0))


[[ True  True  True]
 [ True  True  True]]
True

[[False False False]
 [False False False]]
False


### 두 개의 넘파이 배열의 비교

In [349]:
arr_a = np.array([1, 1, 3, 4, 5])
arr_b = np.array([3, 3, 3, 0, 5])
# 같은 위치를 기준으로 값이 같으면 True
arr_a == arr_b

array([False, False,  True, False,  True])

### 논리 연산 함수
- np.logical_and (조건식1, 조건식2)
- np.logical_not (조건식)
- np.logical_or (조건식1, 조건식2)

In [353]:
arr = np.array([7, 93, 10, 59, 81])
np.logical_and(arr>10, arr<60)

array([False, False, False,  True, False])

In [354]:
np.logical_or(arr<10, arr>60)

array([ True,  True, False, False,  True])

In [355]:
np.logical_not(arr == 10)

array([ True,  True, False,  True,  True])

### np.where()
- np.where(조건식, True, False) : 조건식에 만족하면 True 해당하는 값 표시, 그렇지 않으면 False에 해당하는 값 표시
- np.where(조건식) : 조건식에 만족하면 값 표시

In [356]:
arr = np.array([7, 93, -10, -59, 81])
# 양수면 참, 음수면 거짓
np.where(arr>0, '참', '거짓')

array(['참', '참', '거짓', '거짓', '참'], dtype='<U2')

In [359]:
# 넘파이 배열에서 조건식에 만족하는 값의 인덱스가 반환
arr = np.array([7, 93, -10, -59, 81])
# 조건에 만족하는 인덱스가 반환
print(np.where(arr>0))
# 실제값은?
print(arr[np.where(arr>0)])

(array([0, 1, 4], dtype=int64),)
[ 7 93 81]


###  np.NaN 과 np.isnan()
- 넘파이배열에서 Null 값은? np.NaN
- np.isnan(넘파이배열명)
- Null 값인지 True / False로 표시

In [360]:
np.NaN, type(np.NaN)

(nan, float)

In [361]:
# np.NaN 이 삽입된 넘파이 배열 생성 
arr = np.array([ 7, 93, np.NaN, np.NaN, 81])
arr

array([ 7., 93., nan, nan, 81.])

In [362]:
# np.NaN 값은 비교연산자를 적용할 수 없다.
arr == np.NaN

array([False, False, False, False, False])

In [364]:
# nan 이면 True, 아니면 False
np.isnan(arr)

array([False, False,  True,  True, False])

In [365]:
# 배열에 다시 적용 = 배열명[np.isnan(배열명)]
arr[np.isnan(arr)]

array([nan, nan])

### 넘파이의 인덱싱
- 일반 인덱싱
    - 넘파이배열[행, 열], 넘파이배열[행][열]

- 불린 인덱싱 (Boolean Indexing)
    - 넘파이배열[조건식]

- 팬시 인덱싱 (Fancy Indexing)
    - 넘파이배열[ 넘파이정수배열 ]

In [368]:
# 일반 인덱싱 - 1차원
arr = np.random.randint(1, 100, 10)
print(arr)
print(arr[1])

[29 10 63 56 46 50 33 79 70 58]
10


In [391]:
# 불린 인덱싱 : 넘파이배열[조건식] - 1차원
# 조건식에서 True인 값만 출력
# 50이상의 값만 추출하려면?
print(arr>=50)
print(arr[arr>=50])

[False False  True  True False  True False  True  True  True]
[63 56 50 79 70 58]


In [394]:
# 일반 인덱싱 - 2차원
arr = np.random.randint(1, 100, (3,3))
print(arr)
print(arr[1,1], arr[1][1])

[[84 65 42]
 [44 87 53]
 [97 79 49]]
87 87


In [395]:
# 불린 인덱싱 : 넘파이배열[조건식] - 2차원
# 조건식에서 True인 값만 출력
# 50이상의 값만 추출하려면?
print(arr>=50)
print(arr[arr>=50])

[[ True  True False]
 [False  True  True]
 [ True  True False]]
[84 65 87 53 97 79]


### 넘파이 배열의 논리 연산자 
- |(or 연산자), &(and 연산자), ~(not 연산자) 가능

In [399]:
# 파이썬의 논리 연산자
x = 100
# 50 < x < 70
print((x>50) and (x<70))
print((x>50) or (x<70))
print(not(x>50))

False
True
False


In [415]:
# 넘파이 배열의 논리연산자
arr = np.random.randint(-100, 100, 10)
print(arr)
print(arr>0)
print(arr[arr>0])

[ -4  48  -1  90   9  26 -84  43 -62  33]
[False  True False  True  True  True False  True False  True]
[48 90  9 26 43 33]


In [423]:
# 1~10 사이의 숫자만
# ValueError: The truth value of an array with more than one element is ambiguous.
# Use a.any() or a.all()
# print((arr>1) and (arr<=10))
print((arr>1) & (arr<=10))
print(arr[(arr>1) & (arr<=10)])

[False False False False  True False False False False False]
[9]


In [428]:
# 50보다 크거나 -70보다 작거나
print((arr>=10) | (arr<=-70))
print(arr[(arr>=10) | (arr<=-70)])

[False  True False  True False  True  True  True False  True]
[ 48  90  26 -84  43  33]


In [430]:
# 50보다 크거나 -70보다 작은 숫자는 제외
# not 대신 ~
print(~((arr>=10) | (arr<=-70)))
print(arr[~((arr>=10) | (arr<=-70))])

[ True False  True False  True False False False  True False]
[ -4  -1   9 -62]


### Fancy Index
- 배열을 index value로 사용해서 값을 얻는 방법
- 넘파이배열1[정수형넘파이배열]
- 넘파이배열1[정수형넘파이배열1, 정수형넘파이배열2]

In [431]:
# 1차원 배열 테스트
arr = np.random.randint(-100, 100, 10)
print(arr)

[ -98  -91   78   33  -29   -6   12 -100   25   28]


In [433]:
arr[0]

-98

In [432]:
# 넘파이배열명[[인덱스1, 인덱스2 .....]]
arr[[0, 2, 2, 5]]

array([-98,  78,  78,  -6])

In [441]:
# 2차원 배열 테스트
# 넘파이배열명[[인덱스1, 인덱스2 .....],[인덱스1, 인덱스2 .....]]
arr = np.arange(1, 10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [444]:
arr[2,2], arr[2][2], arr[-1][-1]

(9, 9, 9)

In [446]:
# 대각선 방향으로 추출 (0,0), (1, 1), (2,2)
arr[[0, 1, 2],[0, 1, 2]]

array([1, 5, 9])

In [447]:
# 대각선 방향으로 추출 (0,0), (1, 1), (2,2)
arr[[0, 1, 2, 2],[0, 1, 2, 2]]

array([1, 5, 9, 9])

### 외부파일을 넘파이배열로 생성하기
```
배열명변수 = np.loadtxt('파일경로', 
                        delimiter='구분자',
                        dtype=데이타형)
```

In [449]:
# 현재위치확인

In [450]:
ls

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 629C-402A

 C:\Users\pusan\Desktop\workspace202205\03_DS 디렉터리

2022-06-17  오후 04:36    <DIR>          .
2022-06-17  오후 04:36    <DIR>          ..
2022-06-17  오전 09:23    <DIR>          .ipynb_checkpoints
2022-06-16  오후 04:00    <DIR>          data
2022-06-16  오후 05:30            93,310 np_01.ipynb
2022-06-17  오후 04:36            73,319 np_02.ipynb
2022-06-16  오후 03:41           607,605 Numpy_Quiz.html
2022-06-16  오전 11:44           862,310 Numpy_수업자료1.html
2022-06-16  오후 02:48           652,266 Numpy_수업자료2.html
2022-06-16  오후 03:39           845,201 Numpy_수업자료3.html
               6개 파일           3,134,011 바이트
               4개 디렉터리  424,307,269,632 바이트 남음


In [452]:
# 데이타 확인

In [451]:
ls data\*.dat

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 629C-402A

 C:\Users\pusan\Desktop\workspace202205\03_DS\data 디렉터리

2016-07-17  오후 09:46           171,308 movies.dat
2018-04-24  오후 07:42        24,594,131 ratings.dat
2016-07-17  오후 09:46           134,368 users.dat
               3개 파일          24,899,807 바이트
               0개 디렉터리  424,305,537,024 바이트 남음


### data/ratings.dat
### 데이타형태 - :: 구분자
```
ratings.dat => 무비렌즈의 영화평점데이타 
(userId / movieId/rating/ timestamp)
 1::1193::5:: 978300760
```

In [454]:
# data\ratings.dat => arr
arr = np.loadtxt('data/ratings.dat',delimiter='::', dtype=int)
arr.shape

(1000209, 4)

In [455]:
arr.ndim, arr.dtype

(2, dtype('int32'))

In [456]:
# 맨앞 5개만 출력
arr[:5]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291]])

In [457]:
# 맨 뒷5개만 출력
arr[-5:]

array([[     6040,      1091,         1, 956716541],
       [     6040,      1094,         5, 956704887],
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]])

In [462]:
# 전체 평점의 평균
# 평점의 열만 출력
print(arr[:,2])
# 전체 평점의 평균
print(round(arr[:,2].mean(),2))

[5 3 3 ... 5 4 4]
3.58


In [463]:
# userid 열만 출력
print(arr[:,0])

[   1    1    1 ... 6040 6040 6040]


In [470]:
# userid 열에서 중복값 제거
print(np.unique((arr[:,0])))
# 총 사용자수는?
print(np.unique((arr[:,0])).size)

[   1    2    3 ... 6038 6039 6040]
6040


In [479]:
# 1번 아이디의 사용자의 데이타 출력
user1_data = arr[arr[:,0] == 1]
user1_data.shape

(53, 4)

In [484]:
# 1번 아이디의 사용자의 평점의 평균
print(round(user1_data[:,2].mean(),2))
# 1번 아이디의 사용자의 평점의 최고점
print(user1_data[:,2].max(), user1_data[:,2].min())

4.19
5 3


In [485]:
user1_data[:5]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291]])

In [486]:
# 1번 아이디의 사용자가 최고점을 준 데이타만 출력
user1_data[user1_data[:,2] == user1_data[:,2].max()]

array([[        1,      1193,         5, 978300760],
       [        1,      2355,         5, 978824291],
       [        1,      1287,         5, 978302039],
       [        1,      2804,         5, 978300719],
       [        1,       595,         5, 978824268],
       [        1,      1035,         5, 978301753],
       [        1,      3105,         5, 978301713],
       [        1,      1270,         5, 978300055],
       [        1,       527,         5, 978824195],
       [        1,        48,         5, 978824351],
       [        1,      1836,         5, 978300172],
       [        1,      1022,         5, 978300055],
       [        1,       150,         5, 978301777],
       [        1,         1,         5, 978824268],
       [        1,      1961,         5, 978301590],
       [        1,      1028,         5, 978301777],
       [        1,      1029,         5, 978302205],
       [        1,      2028,         5, 978301619]])