In [3]:
# 쥬피터 노트북 셀 크기 설정 
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; font-weight:bold }</style>"))

# 경고 메세지 X
import warnings
warnings.filterwarnings(action='ignore')

import numpy as np

In [4]:
# 퀴즈 2
# 다음 리스트를 이용하여 7개의 이름으로 구성된 리스트를 생성하여라.
# 이때 최종 결과는 중복 이름이 없어야하며 넘파이 배열이어야한다

# ['박', '김', '이', '최', '신', '장', '윤']
# ['은', '강', '종', '영', '준', '민']
# ['철','수', '미', '원', '주', '혁', '희', '수']

# >>> 생성된 이름 예시 
# ['박영수', '박준혁', '신영수', '신종주', '이민수', '이종혁', '최강철']

In [6]:
# 중복이 있는 형태라면

# 넘파이 배열 생성
first_name = np.array(['박', '김', '이', '최', '신', '장', '윤'])
last_name1 = np.array(['은', '강', '종', '영', '준', '민'])
last_name2 = np.array(['철','수', '미', '원', '주', '혁', '희', '수'])

# 빈 넘파이 배령 생성 => 문자열형
name_list = np.array([], dtype='<U3')
print(name_list, name_list.dtype)
x = np.random.choice(first_name)
y = np.random.choice(last_name1)
z = np.random.choice(last_name2)

# 한개만 생성
temp = x + y + z
print(temp)
name_list = np.insert(name_list, len(name_list), temp)
name_list

[] <U3
이은미


array(['이은미'], dtype='<U3')

In [5]:
# 넘파이 배열은 데이타형의 기본형이 실수형이다
name_list = np.array([])
name_list.dtype

dtype('float64')

In [7]:
# 중복 확인
first_name = np.array(['박', '김', '이', '최', '신', '장', '윤'])
last_name1 = np.array(['은', '강', '종', '영', '준', '민'])
last_name2 = np.array(['철','수', '미', '원', '주', '혁', '희', '수'])

name_list = np.array([], dtype='<U3')

# 100 개 정도 생성하면 중복값이 나타난다 
for i in range(100):
    x = np.random.choice(first_name)
    y = np.random.choice(last_name1)
    z = np.random.choice(last_name2)
    temp = x + y + z
    name_list = np.insert(name_list, len(name_list), temp)
        
len(name_list), np.sort(name_list)

(100,
 array(['김강수', '김강희', '김민철', '김민철', '김민혁', '김영미', '김은미', '김종원', '김준미',
        '김준수', '김준주', '박강수', '박영미', '박영주', '박영주', '박은수', '박은수', '박은원',
        '박은철', '박종수', '박종철', '박준수', '박준원', '박준희', '신강원', '신강희', '신민원',
        '신민주', '신민주', '신민희', '신영수', '신영주', '신은미', '신은수', '신은혁', '신종원',
        '신종주', '신준수', '신준수', '윤강주', '윤강혁', '윤강희', '윤민주', '윤민희', '윤영미',
        '윤영혁', '윤은수', '윤은원', '윤은철', '윤은혁', '윤종수', '윤종수', '윤종수', '윤종희',
        '윤준수', '윤준수', '이강미', '이강수', '이강혁', '이민원', '이영미', '이영원', '이은수',
        '이은희', '이은희', '이종수', '이종주', '이종혁', '이준원', '이준혁', '장강미', '장강수',
        '장강수', '장강주', '장강혁', '장강희', '장민수', '장민혁', '장영수', '장영주', '장영희',
        '장은수', '장은철', '장은철', '장종수', '장종수', '장종원', '장종철', '장준수', '장준수',
        '장준희', '최강수', '최강희', '최민혁', '최민혁', '최은수', '최은철', '최은희', '최준혁',
        '최준희'], dtype='<U3'))

In [13]:
# 중복이 없는 형태로 변경

# 1) 넘파이 배열 생성
first_name = np.array(['박', '김', '이', '최', '신', '장', '윤'])
last_name1 = np.array(['은', '강', '종', '영', '준', '민'])
last_name2 = np.array(['철','수', '미', '원', '주', '혁', '희', '수'])

# 2) 문자열 형태의 넘파이 배열 생성
name_list = np.array([], dtype='<U3')

# 3) 중복이 없다면 추가, 넘파이 길이가 7이면 while문 탈출
while True:
    x = np.random.choice(first_name)
    y = np.random.choice(last_name1)
    z = np.random.choice(last_name2)
    temp = x + y + z
    if len(name_list) >= 7:
        break
    if temp not in name_list:
        name_list = np.insert(name_list, len(name_list), temp)
        
# 4) 출력
len(name_list), np.sort(name_list)

(7, array(['박영철', '신준희', '윤종희', '이민미', '장영원', '장은수', '최종수'], dtype='<U3'))

In [14]:
# Quiz : 상위 15퍼센트에 해당하는 숫자 추출하기
# 1) 1~100사이에서 50개의 정수난수로 된 넘파이 배열 생성 (중복 숫자 없이 생성)
# 2) 역순 소팅 (가장 큰값이 가장 먼저나온다) 
# 3) 전체길이를 구한 후 상위 15%에 해당하는 값만 표시

In [15]:
# 중복값이 생기는가?
matrix_50 = np.random.randint(1,101,50)
print(matrix_50)
print(len(matrix_50))
print(len(np.unique(matrix_50)))

[75 40 29 14 36  9 46  9 26 45 27 31 40 30 96 92 46 15 18 53 14 51  8 12
 64 52 66 32  6 51 50 64 79  7 43 83 96 85  8 77 32 10 91 22 91 41 71 81
 54 87]
50
40


In [19]:
# 1) 중복값 없이 숫자 생성 1
matrix_50 = np.arange(1,101)
np.random.shuffle(matrix_50)
print(matrix_50)
print(matrix_50[:50])

[  4  43  84  91  83  64  36  37  54  69  13  61  55  53  48  76   7  59
   6  32   2  39  10  58  18  80 100  99  88  19  16  31  81  62  26  82
  51  95  97  56   5  74  65  68  52  78  86  93  75  40  33  11  89  29
  71  87  44   3  12  96   8  47  60  46  30   1  94  63  22  85  27  45
  57  41  21  35  79  23  34  49  50  66  70  92  20  14  38  73  98  15
  67  72  24  28  42  17  90   9  77  25]
[  4  43  84  91  83  64  36  37  54  69  13  61  55  53  48  76   7  59
   6  32   2  39  10  58  18  80 100  99  88  19  16  31  81  62  26  82
  51  95  97  56   5  74  65  68  52  78  86  93  75  40]


In [25]:
# 1) 중복값 없이 숫자 생성 2
matrix_50 = np.random.choice(matrix_50, size=50, replace=False)
matrix_50

array([ 51,  80,  24,  93,  11,  17,  92,   4, 100,  22,  29,  81,  76,
        50,  40,  56,  57,  72,  75,  97,  62,  66,  65,  77,  55,  96,
        27,  58,  32,   9,  43,  82,  15,  70,  64,   7,  48,  49,  33,
        28,  61,   2,  38,  23,  84,  73,  13,  16,  46,  63])

In [26]:
# 2) 역순 소팅 (가장 큰값이 가장 먼저나온다)
matrix_50 = np.sort(matrix_50)[::-1]
matrix_50

array([100,  97,  96,  93,  92,  84,  82,  81,  80,  77,  76,  75,  73,
        72,  70,  66,  65,  64,  63,  62,  61,  58,  57,  56,  55,  51,
        50,  49,  48,  46,  43,  40,  38,  33,  32,  29,  28,  27,  24,
        23,  22,  17,  16,  15,  13,  11,   9,   7,   4,   2])

In [27]:
# 3) 전체길이를 구한 후 상위 15%에 해당하는 값만 표시
print(0.15*len(matrix_50))
n = int(0.15*len(matrix_50))
n

7.5


7

In [28]:
matrix_50[0:n]

array([100,  97,  96,  93,  92,  84,  82])

In [29]:
kor = np.array( [60,55,70,30,20,90])

# 1. 국어점수가 가장큰값을 구하시요
kor.max(), np.max(kor)

(90, 90)

In [30]:
# 2. 국어점수가 80점이상인 값을 구하시요
kor[ kor>=80 ]

array([90])

In [ ]:
# 3. 국어 점수가 50점이상 80점 이하인 값을 구하시요
kor[ (kor>=50) & (kor<=80) ]

In [31]:
# 4. 국어점수의 평균을 구하시요
kor.mean()

54.166666666666664

In [32]:
# 5. 국어점수의 총합을 구하시요.
kor.sum()

325

In [33]:
# 6. 국어점수가 40점이하인 데이터를 삭제하시요
np.delete(kor, np.where( kor<=40))

array([60, 55, 70, 90])

In [34]:
np.where( kor<=40), kor[np.where( kor<=40)], kor[kor<=40]

((array([3, 4], dtype=int64),), array([30, 20]), array([30, 20]))

In [35]:
# np.delete(넘파이배열, 삭제인덱스 )
np.delete(kor, np.where( kor<=40) )

array([60, 55, 70, 90])

In [36]:
# 7. 국어점수가 50점이상인 데이터에 가산점 10%를  부여하시요
kor[ kor>=50]*1.1

array([66. , 60.5, 77. , 99. ])

In [37]:
# 배열에 적용
# np.where(조건식, 참일때결과, 거짓일때결과)
np.where(kor>=50, kor*1.1, kor)

array([66. , 60.5, 77. , 30. , 20. , 99. ])

In [38]:
kor3 = np.where(kor>=50, kor*1.1, kor)
kor3

array([66. , 60.5, 77. , 30. , 20. , 99. ])

In [40]:
# 8. 국어점수 top 3를 구하시요
np.sort(kor)

array([20, 30, 55, 60, 70, 90])

In [41]:
# np.sort(kor)[-1:-6:-1]
np.sort(kor)[-1:-4:-1]

array([90, 70, 60])

In [42]:
np.sort(kor)[::-1][:3]

array([90, 70, 60])

In [ ]:
# 9. 국어점수가 70점이상이면 '합격' , 아니면 '불합격으로'
# 아래와 같이 출력하시요
# 60 '불합격'
# 55 '불합격'

In [39]:
for n in kor:
    if n>=70: 
        print(n, '합격')
    else:
        print(n, '불합격')

60 불합격
55 불합격
70 합격
30 불합격
20 불합격
90 합격


In [43]:
print(np.where(kor>=70, f'{kor} 합격', f'{kor} 불합격'))

['[60 55 70 30 20 90] 불합격' '[60 55 70 30 20 90] 불합격'
 '[60 55 70 30 20 90] 합격' '[60 55 70 30 20 90] 불합격'
 '[60 55 70 30 20 90] 불합격' '[60 55 70 30 20 90] 합격']


In [ ]:
# 데이타 확인

In [46]:
ls data\*.csv

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 629C-402A

 C:\Users\pusan\Desktop\workspace202205\03_DS\data 디렉터리

2021-01-03  오전 01:34           219,901 201902_201902_연령별인구현황_월간.csv
2019-03-05  오전 04:05         2,317,454 age.csv
2021-05-29  오전 12:48         3,392,006 air_test.csv
2018-09-05  오후 08:23            90,508 billboard.csv
2020-08-14  오전 08:41             1,135 CCTV_in_Seoul.csv
2018-09-06  오전 05:23             5,796 country_timeseries.csv
2021-11-23  오전 09:25            35,455 Jeju2021.csv
2018-09-05  오후 08:23               984 pew.csv
2020-08-17  오후 06:02             3,537 police.csv
2019-08-04  오전 01:36               528 population_in_Inchon.csv
2022-05-17  오전 03:58               492 resultRatings2.csv
2020-08-13  오전 07:28               442 scientists.csv
2019-03-20  오후 07:54         1,185,149 seoul.csv
2021-05-29  오전 12:48             1,984 seoul_crime.csv
2021-02-01  오전 05:49            93,805 seoul2021.csv
2020-12-05  오전 05:52            97,152 seoul-covid19_6_30_.csv
2020-12-05  오

In [47]:
!type data\Jeju2021.csv

10,제주,2021-01-01,6.8,9.9,18.2,제주,4,-4.6,성산,,,
10,제주,2020-12-01,8,11.3,16.3,성산,5.1,-2.8,성산,,,
10,제주,2020-11-01,14.6,17.8,26.7,제주,11.6,4.8,성산,,,
10,제주,2020-10-01,18.5,21.7,25.8,고산,15.7,10.2,성산,,,
10,제주,2020-09-01,22.5,25.4,32.5,고산,20.1,14.9,성산,,,
10,제주,2020-08-01,28.4,31.2,36.3,제주,26.2,22.3,성산,,,
10,제주,2020-07-01,23.8,26.5,34.3,제주,21.7,16.8,성산,,,
10,제주,2020-06-01,22.4,25.7,30.9,제주,20,11.7,성산,,,
10,제주,2020-05-01,18.8,22.7,29.5,제주,15.7,10.3,성산,,,
10,제주,2020-04-01,13.6,17.3,24.8,제주,10.1,4.5,성산,,,
10,제주,2020-03-01,11.9,15.3,23.2,제주,8.4,1.2,성산,,,
10,제주,2020-02-01,9.4,12.8,21.8,제주,6.2,-0.7,성산,,,
10,제주,2020-01-01,9.2,11.7,23.6,제주,6.8,0.4,성산,,,
10,제주,2019-12-01,10.2,13.4,19.8,서귀포,7.3,0.4,성산,,,
10,제주,2019-11-01,15.1,18.8,24.3,제주,11.9,4.4,성산,,,
10,제주,2019-10-01,19.9,23.1,28,성산,17,9.3,성산,,,
10,제주,2019-09-01,24.1,26.8,30.4,제주,22,15.1,성산,,,
10,제주,2019-08-01,27.4,30.2,34.7,제주,25.2,18.5,성산,,,
10,제주,2019-07-01,24.7,27.3,35.4,제주,22.9,17.5,성산,,,
10,제주,2019-06-01,21.6,24.8,29.8,제주,19.1,13.7,성산,,,
10,제주,201

10,제주,1981-02-01,5.8,8.9,16.2,서귀포,2.4,-5.7,성산,성산포,,
10,제주,1981-01-01,4.1,7.4,15,서귀포,0.8,-5,성산,성산포,,
10,제주,1980-12-01,6.3,9.7,17.5,서귀포,3,-2.3,성산,성산포,,
10,제주,1980-11-01,13.5,17.7,23.3,서귀포,9.5,2.7,성산,성산포,,
10,제주,1980-10-01,17.6,20.9,27.2,제주,14,5.1,성산,성산포,,
10,제주,1980-09-01,21.5,24.9,30,서귀포,18.1,10.9,성산,성산포,,
10,제주,1980-08-01,23.8,26.3,31.9,제주,21.4,17.3,성산,성산포,,
10,제주,1980-07-01,24.2,26.9,32.6,제주,21.9,17.9,성산,성산포,,
10,제주,1980-06-01,21.4,24.7,30.1,제주,18.7,10.6,성산,성산포,,
10,제주,1980-05-01,17.5,21.3,28.9,제주,13.4,5.4,성산,성산포,,
10,제주,1980-04-01,13.7,17.2,23.9,제주,9.5,-0.5,성산,성산포,,
10,제주,1980-03-01,9.2,12.4,17.3,서귀포,5.6,-0.4,성산,성산포,,
10,제주,1980-02-01,4.8,8,17.1,제주,1.5,-3.4,서귀포,,,
10,제주,1980-01-01,6.3,9.2,17.2,서귀포,3.3,-4.8,성산,성산포,,
10,제주,1979-12-01,9.5,13.2,20.2,제주,5.9,-0.7,성산,성산포,,
10,제주,1979-11-01,12.6,16.2,26.3,서귀포,8.9,0.4,성산,성산포,,
10,제주,1979-10-01,19,23.3,27,서귀포,14.5,6.4,성산,성산포,,
10,제주,1979-09-01,22.7,26,30.5,제주,19.5,14.4,성산,성산포,,
10,제주,1979-08-01,26.5,29.7,35.2,제주,23.3,15.8,제주,,,
10,제주,1979-07-0

In [49]:
# 2, 3, 5, 8 컬럼만 넘파이배열로 저장 <= 문자열
data = np.loadtxt('data/jeju2021.csv', delimiter=',' , dtype=np.str ,usecols=(2,3,5,8))
data.shape, data.dtype

((583, 4), dtype('<U10'))

In [53]:
data[:5]

array([['2021-01-01', '6.8', '18.2', '-4.6'],
       ['2020-12-01', '8', '16.3', '-2.8'],
       ['2020-11-01', '14.6', '26.7', '4.8'],
       ['2020-10-01', '18.5', '25.8', '10.2'],
       ['2020-09-01', '22.5', '32.5', '14.9']], dtype='<U10')

In [52]:
data[-10:]

array([['1973-04-01', '14.8', '24.3', '2.9'],
       ['1973-03-01', '9.6', '22.9', '-2'],
       ['1973-02-01', '7.6', '19.1', '4.3'],
       ['1973-01-01', '7.5', '19.6', '-1.6'],
       ['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U10')

In [ ]:
# 2) 1)의 넘파이 배열의 데이타 형태를 실수 형태로 변경하여라 
#   데이타의 결측치나 이상값은 -99로 지정한다. 

In [54]:
# 1) 리스트 형태로 전처리
result = []
for row in data:
    temp = []
    try:
        # 날짜 - 삭제
        if row[0]:
            date = float(row[0].replace('-','').replace('-',''))
        else:
            date=-99
        temp.append(date)
        # 나머지 온도 데이타
        for item in row[1:]:
            
            try:
                temp.append(float(item))
            except:
                temp.append(-99)

#             if item == '':
#                 temp.append(-99)
#             else:
#                 temp.append(float(item))
    except:
        pass
    else:
        result.append(temp) 

In [55]:
len(data), len(result)

(583, 583)

In [56]:
result[-7:]

[[19730101.0, 7.5, 19.6, -1.6],
 [-99, -99, -99, -99],
 [-99, -99, -99, -99],
 [-99, -99, -99, -99],
 [-99, -99, -99, -99],
 [-99, -99, -99, -99],
 [-99, -99, -99, -99]]

In [57]:
# 2) 넘파이 배열로 변경
arr_jeju = np.array(result)
arr_jeju

array([[ 2.0210101e+07,  6.8000000e+00,  1.8200000e+01, -4.6000000e+00],
       [ 2.0201201e+07,  8.0000000e+00,  1.6300000e+01, -2.8000000e+00],
       [ 2.0201101e+07,  1.4600000e+01,  2.6700000e+01,  4.8000000e+00],
       ...,
       [-9.9000000e+01, -9.9000000e+01, -9.9000000e+01, -9.9000000e+01],
       [-9.9000000e+01, -9.9000000e+01, -9.9000000e+01, -9.9000000e+01],
       [-9.9000000e+01, -9.9000000e+01, -9.9000000e+01, -9.9000000e+01]])

In [60]:
# 3)
# 넘파이배열 표시 셋팅
np.set_printoptions(precision=3)
np.set_printoptions(formatter={'float_kind': lambda x: "{0:0.3f}".format(x)})

In [59]:
arr_jeju

array([[20210101.000, 6.800, 18.200, -4.600],
       [20201201.000, 8.000, 16.300, -2.800],
       [20201101.000, 14.600, 26.700, 4.800],
       ...,
       [-99.000, -99.000, -99.000, -99.000],
       [-99.000, -99.000, -99.000, -99.000],
       [-99.000, -99.000, -99.000, -99.000]])

In [ ]:
# 4) 제주도의 최고 기온은? 그리고 날짜는?

In [61]:
# '일시', '평균기온(℃)', '최고기온(℃)', '최저기온(℃)'
arr_jeju[:3]

array([[20210101.000, 6.800, 18.200, -4.600],
       [20201201.000, 8.000, 16.300, -2.800],
       [20201101.000, 14.600, 26.700, 4.800]])

In [62]:
# 제주도의 최고기온
arr_jeju_max = np.max(arr_jeju[:,2])
arr_jeju_max

37.4

In [64]:
# 최고기온 데이타
arr_jeju[arr_jeju[:, 2]==arr_jeju_max]

array([[19980801.000, 27.900, 37.400, 19.100]])

In [65]:
arr_jeju_max_date = str(int(arr_jeju[arr_jeju[:, 2]==arr_jeju_max][0, 0]))
arr_jeju_max_date

'19980801'

In [66]:
# 5) 2018년도 제주도 기온 데이타만 출력하여라

In [67]:
arr_jeju2018 = arr_jeju[(arr_jeju[:, 0] >= 20180000) & (arr_jeju[:, 0] < 20190000)]
arr_jeju2018

array([[20181201.000, 9.300, 22.900, -1.000],
       [20181101.000, 14.200, 21.800, 3.800],
       [20181001.000, 17.900, 27.000, 7.900],
       [20180901.000, 23.700, 31.200, 21.300],
       [20180801.000, 28.300, 35.500, 22.300],
       [20180701.000, 27.000, 35.000, 19.400],
       [20180601.000, 22.200, 32.300, 13.100],
       [20180501.000, 18.900, 31.100, 6.700],
       [20180401.000, 15.900, 26.100, 0.500],
       [20180301.000, 11.600, 23.200, 1.700],
       [20180201.000, 5.900, 17.500, -3.800],
       [20180101.000, 5.400, 16.200, -3.700]])

In [68]:
# 6) 최저 기온이 -5도 이하인 데이타만 출력하여라.

In [69]:
arr_jeju[arr_jeju[:, 3] <= -5]

array([[20160101.000, 6.200, 17.500, -6.900],
       [20080401.000, 14.700, 22.600, -99.000],
       [20050801.000, 26.800, 34.700, -99.000],
       [20010201.000, 7.600, 22.600, -5.100],
       [20000801.000, 28.200, 33.400, -99.000],
       [19900101.000, 5.600, 18.600, -7.000],
       [19891101.000, 12.900, 25.000, -99.000],
       [19810301.000, 10.000, 20.000, -99.000],
       [19810201.000, 5.800, 16.200, -5.700],
       [19810101.000, 4.100, 15.000, -5.000],
       [19770201.000, 4.500, 17.500, -6.400],
       [19760101.000, 4.900, 15.200, -99.000],
       [-99.000, -99.000, -99.000, -99.000],
       [-99.000, -99.000, -99.000, -99.000],
       [-99.000, -99.000, -99.000, -99.000],
       [-99.000, -99.000, -99.000, -99.000],
       [-99.000, -99.000, -99.000, -99.000],
       [-99.000, -99.000, -99.000, -99.000]])

In [70]:
arr_jeju[(arr_jeju[:, 3] <= -5) & (arr_jeju[:, 3] > -99)]

array([[20160101.000, 6.200, 17.500, -6.900],
       [20010201.000, 7.600, 22.600, -5.100],
       [19900101.000, 5.600, 18.600, -7.000],
       [19810201.000, 5.800, 16.200, -5.700],
       [19810101.000, 4.100, 15.000, -5.000],
       [19770201.000, 4.500, 17.500, -6.400]])

In [71]:
# 7) 2018년도 기온 데이타에서 최고 기온이 28도 보다 높은 경우의 데이타만 출력하여라.

In [72]:
arr_jeju2018[arr_jeju2018[:, 2] >= 28 ]

array([[20180901.000, 23.700, 31.200, 21.300],
       [20180801.000, 28.300, 35.500, 22.300],
       [20180701.000, 27.000, 35.000, 19.400],
       [20180601.000, 22.200, 32.300, 13.100],
       [20180501.000, 18.900, 31.100, 6.700]])