In [2]:
# 쥬피터 노트북 셀 크기 설정 
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; font-weight:bold }</style>"))

# 경고 메세지 X
import warnings
warnings.filterwarnings(action='ignore')

### Q1 넘파이 모듈을 np 별칭으로 임포트해라

In [4]:
import numpy as np

#### Q2 다음과 같은 리스트를 이용하여
-  넘파이 배열을 만들고
-  전체 갯수, 차원, 데이터형, 구조를 출력하여라
-  ['강아지', '원숭이', '꽃', '45', '100']

-  array(['강아지', '원숭이', '꽃', '45', '100'], dtype='<U3')
-  차원 ? 1
-  전체 갯수 ? 5
-  데이터형 ? <U3

In [10]:
mylist = ['강아지', '원숭이', '꽃', '45', '100']
arr = np.array(mylist)
print('차원 ?', arr.ndim)
print('전체 갯수 ?', arr.size)
print('데이터형 ?', arr.dtype)

차원 ? 1
전체 갯수 ? 5
데이터형 ? <U3


### Q3 np.ones()를 이용하여
- 2행 3열의 넘파이 배열을 생성하여라
- 
- array([[1., 1., 1.],
-        [1., 1., 1.]])

In [17]:
arr = np.ones([2,3])
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


### Q4. np.arange(), np.reshape()를 이용하여
- 다음과 같은 넘파이 배열을 생성하여라
- array([[51, 52, 53, 54, 55],
-        [56, 57, 58, 59, 60],
-        [61, 62, 63, 64, 65],
-        [66, 67, 68, 69, 70],
-        [71, 72, 73, 74, 75],
-        [76, 77, 78, 79, 80]])

In [25]:
arr = np.arange(51,81).reshape([6,5])
arr

array([[51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75],
       [76, 77, 78, 79, 80]])

### Q5. Q4의 넘파이 배열의 자료형을
- float로 변경하고 데이터형을 출력하여라
- 
- array([[51., 52., 53., 54., 55.],
-        [56., 57., 58., 59., 60.],
-        [61., 62., 63., 64., 65.],
-        [66., 67., 68., 69., 70.],
-        [71., 72., 73., 74., 75.],
-        [76., 77., 78., 79., 80.]])
- -------------------------------------  
- dtype('float64')

In [29]:
arr = np.arange(51,81, dtype=float).reshape([6,5])
arr.dtype

dtype('float64')

In [58]:
list = [ 1,  4,  5,  6],[56, 23, 45, 67],[ 8,  4,  6, 10]
arr = np.array(list)
arr[0]

array([ 9,  8, 11, 16])

In [80]:
arr = arr.flatten()
arr

array([ 1,  4,  5,  6, 56, 23, 45, 67,  8,  4,  6, 10])

In [81]:
arr[5:11]

array([23, 45, 67,  8,  4,  6])

In [147]:
arr1 = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [148]:
arr1[0]=10
arr1[7:]=0
arr1

array([10,  2,  3,  4,  5,  6,  7,  0,  0,  0])

In [96]:
import random

In [163]:
arr = np.random.randint(10,99,(5,5))
print(arr)

[[56 58 50 15 29]
 [13 93 57 65 97]
 [33 69 60 59 62]
 [55 40 76 95 73]
 [58 21 91 29 36]]


In [ ]:
Q9. 1~100 사이의 정수중 7개의 숫자를 무작위로 추출한 후 가장 큰값과 가장 작은 값을 출력하여라.

In [169]:
arr = np.random.randint(1,100,7)
arr

array([16, 27, 60,  9, 33, 51, 55])

In [170]:
print(arr.max(),arr.min())

60 9


In [197]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
arr3 = np.arange(21,30).reshape(3,3)
arr1,arr2,arr3

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]),
 array([[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]))

In [198]:
np.hstack((arr1, arr2, arr3))

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26],
       [ 7,  8,  9, 17, 18, 19, 27, 28, 29]])

In [199]:
np.vstack((arr1, arr2, arr3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])