In [2]:
# 쥬피터 노트북 셀 크기 설정 
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; font-weight:bold }</style>"))
# 경고 메세지 숨기기 
import warnings
warnings.filterwarnings(action='ignore')

In [8]:
import numpy as np
import pandas as pd

### 그룹화 - groupby()
- 데이타프레임.groupby(컬럼명).컬럼명.집계함수
- 그룹객체명 = 데이타프레임.groupby(컬럼명)
- 그룹객체명.집계함수()
- 그룹객체명.agg([집계함수1, 집계함수2...])
- 집계함수의 종류
    - count, size, mean, std, min, max, sum, var

In [4]:
ls data\*.tsv

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 629C-402A

 C:\Users\pusan\Desktop\workspace202205\03_DS\data 디렉터리

2020-08-13  오전 07:28            83,637 gapminder.tsv
               1개 파일              83,637 바이트
               0개 디렉터리  421,446,107,136 바이트 남음


In [5]:
!type data\gapminder.tsv

country	continent	year	lifeExp	pop	gdpPercap
Afghanistan	Asia	1952	28.801	8425333	779.4453145
Afghanistan	Asia	1957	30.332	9240934	820.8530296
Afghanistan	Asia	1962	31.997	10267083	853.10071
Afghanistan	Asia	1967	34.02	11537966	836.1971382
Afghanistan	Asia	1972	36.088	13079460	739.9811058
Afghanistan	Asia	1977	38.438	14880372	786.11336
Afghanistan	Asia	1982	39.854	12881816	978.0114388
Afghanistan	Asia	1987	40.822	13867957	852.3959448
Afghanistan	Asia	1992	41.674	16317921	649.3413952
Afghanistan	Asia	1997	41.763	22227415	635.341351
Afghanistan	Asia	2002	42.129	25268405	726.7340548
Afghanistan	Asia	2007	43.828	31889923	974.5803384
Albania	Europe	1952	55.23	1282697	1601.056136
Albania	Europe	1957	59.28	1476505	1942.284244
Albania	Europe	1962	64.82	1728137	2312.888958
Albania	Europe	1967	66.22	1984060	2760.196931
Albania	Europe	1972	67.69	2263554	3313.422188
Albania	Europe	1977	68.93	2509048	3533.00391
Albania	Europe	1982	70.42	2780097	3630.880722
Albania	Europe	1987	72	3075321	3738.932735

In [13]:
df = pd.read_csv('data/gapminder.tsv', sep='\t')
df.sample(3)

country continent  year  lifeExp      pop    gdpPercap
475              El Salvador  Americas  1987   63.154  4842194  4140.442097
144   Bosnia and Herzegovina    Europe  1952   53.820  2791000   973.533195
1154                    Oman      Asia  1962   43.165   628164  2924.638113

In [14]:
# 범주형 데이타의 그룹핑
# 대륙별 데이타
df['continent'].unique()

array(['Asia', 'Europe', 'Africa', 'Americas', 'Oceania'], dtype=object)

In [15]:
# 년도별 데이타 
df['year'].unique()

array([1952, 1957, 1962, 1967, 1972, 1977, 1982, 1987, 1992, 1997, 2002,
       2007], dtype=int64)

In [17]:
# 나라별 데이타 
df['country'].unique(), df['country'].unique().shape

(array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
        'Australia', 'Austria', 'Bahrain', 'Bangladesh', 'Belgium',
        'Benin', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
        'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon',
        'Canada', 'Central African Republic', 'Chad', 'Chile', 'China',
        'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.',
        'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Czech Republic',
        'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt',
        'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Ethiopia',
        'Finland', 'France', 'Gabon', 'Gambia', 'Germany', 'Ghana',
        'Greece', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Haiti',
        'Honduras', 'Hong Kong, China', 'Hungary', 'Iceland', 'India',
        'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
        'Jamaica', 'Japan', 'Jordan', 'Kenya', 'Korea, Dem. Rep.',
        'Korea, Rep.', 

In [19]:
# 평균수명(lifeExp)의 평균
df['lifeExp'].mean()

59.47443936619714

In [22]:
# 대륙별 평균수명(lifeExp)의 평균
# 데이타프레임.groupby(그룹핑컬럼명).수치형컬럼명.집계함수 => 시리즈 
print(df['year'].unique())
df.groupby('continent').lifeExp.mean()

[1952 1957 1962 1967 1972 1977 1982 1987 1992 1997 2002 2007]


continent
Africa      48.865330
Americas    64.658737
Asia        60.064903
Europe      71.903686
Oceania     74.326208
Name: lifeExp, dtype: float64

In [23]:
# 대륙별 인구의 최대값 
# 데이타프레임.groupby(그룹핑컬럼명).수치형컬럼명.집계함수 => 시리즈 
print(df['continent'].unique())
print()
df.groupby('continent').pop.max()

['Asia' 'Europe' 'Africa' 'Americas' 'Oceania']



continent
Africa       135031164
Americas     301139947
Asia        1318683096
Europe        82400996
Oceania       20434176
Name: pop, dtype: int64

In [29]:
df['continent'].value_counts()

Africa      624
Asia        396
Europe      360
Americas    300
Oceania      24
Name: continent, dtype: int64

In [26]:
# 대륙별 각 년도의 데이터수 출력 
# 데이타프레임.groupby(그룹핑컬럼명).수치형컬럼명.집계함수 => 시리즈 
print(df['year'].unique())
df.groupby('continent').year.count()

[1952 1957 1962 1967 1972 1977 1982 1987 1992 1997 2002 2007]


continent
Africa      624
Americas    300
Asia        396
Europe      360
Oceania      24
Name: year, dtype: int64

In [ ]:
# 그룹 객체화 + 집계함수 
# 1) 그룹객체
#    그룹객체명 = 데이타프레임.groupby(컬럼명)
# 2) 집계함수 적용 
#    그룹객체명.집계함수()

In [31]:
# 1) 그룹객체 생성 - 대륙별
#    그룹객체명 = 데이타프레임.groupby(컬럼명)
group_c = df.groupby('continent')
group_c

In [33]:
# 그룹객체명.groups => (대륙별이 키)
print(type(group_c.groups))
group_c.groups

<class 'pandas.io.formats.printing.PrettyDict'>


{'Africa': [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, ...], 'Americas': [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 432, 433, 434, 435, ...],

In [39]:
# 키로 접근 => 키값에 해당하는 인덱스
group_c.groups['Africa']

Int64Index([  24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
            ...
            1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703],
           dtype='int64', length=624)

In [38]:
df[df['continent'] == 'Africa'].index

Int64Index([  24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
            ...
            1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703],
           dtype='int64', length=624)

In [44]:
# 2) 집계함수 적용 
#    그룹객체명.집계함수() => 데이타프레임
# 모든 수치데이타의 컬럼의 평균 데이타프레임
group_c.mean()

year    lifeExp           pop     gdpPercap
continent                                               
Africa     1979.5  48.865330  9.916003e+06   2193.754578
Americas   1979.5  64.658737  2.450479e+07   7136.110356
Asia       1979.5  60.064903  7.703872e+07   7902.150428
Europe     1979.5  71.903686  1.716976e+07  14469.475533
Oceania    1979.5  74.326208  8.874672e+06  18621.609223

In [43]:
df.groupby('continent').year.mean()

continent
Africa      1979.5
Americas    1979.5
Asia        1979.5
Europe      1979.5
Oceania     1979.5
Name: year, dtype: float64

In [47]:
# 대륙별 lifeExp, pop 컬럼의 평균만 출력
df.groupby('continent').mean()[['lifeExp','pop']]

lifeExp           pop
continent                         
Africa     48.865330  9.916003e+06
Americas   64.658737  2.450479e+07
Asia       60.064903  7.703872e+07
Europe     71.903686  1.716976e+07
Oceania    74.326208  8.874672e+06

In [50]:
# 년도별 lifeExp, pop, gdpPercap 컬럼의 평균만 출력
df.groupby('year').max()[['lifeExp','pop','gdpPercap']]

lifeExp         pop     gdpPercap
year                                   
1952   72.670   556263527  108382.35290
1957   73.470   637408000  113523.13290
1962   73.680   665770000   95458.11176
1967   74.160   754550000   80894.88326
1972   74.720   862030000  109347.86700
1977   76.110   943455000   59265.47714
1982   77.110  1000281000   33693.17525
1987   78.670  1084035000   31540.97480
1992   79.360  1164970000   34932.91959
1997   80.690  1230075000   41283.16433
2002   82.000  1280400000   44683.97525
2007   82.603  1318683096   49357.19017

In [53]:
# 1952년도 평균수명의 최대값 
# 72.670
df.groupby('year').max()[['lifeExp', 'pop', 'gdpPercap' ]].loc[1952, 'lifeExp']

72.67

In [56]:
df[df['year'] == 1952]['lifeExp'].max()

72.67

### 그룹핑 + 다중 집계함수
- 데이타프레임명.groupby(그룹기준의컬럼).agg([집계함수1, 집계함수2 ...])
- 그룹객체명.agg([집계함수1, 집계함수2 ...])
- 집계함수란? sum(), mean(), max(), min(), std(), var(), count()....
- 집계함수 리스트는 넘파이집계함수명을 데이타로 한다 

In [57]:
df.groupby('continent').agg([np.sum, np.mean])

year              lifeExp                     pop                \
               sum    mean          sum       mean          sum          mean   
continent                                                                       
Africa     1235208  1979.5  30491.96600  48.865330   6187585961  9.916003e+06   
Americas    593850  1979.5  19397.62100  64.658737   7351438499  2.450479e+07   
Asia        783882  1979.5  23785.70168  60.064903  30507333901  7.703872e+07   
Europe      712620  1979.5  25885.32700  71.903686   6181115304  1.716976e+07   
Oceania      47508  1979.5   1783.82900  74.326208    212992136  8.874672e+06   

              gdpPercap                
                    sum          mean  
continent                              
Africa     1.368903e+06   2193.754578  
Americas   2.140833e+06   7136.110356  
Asia       3.129252e+06   7902.150428  
Europe     5.209011e+06  14469.475533  
Oceania    4.469186e+05  18621.609223

In [61]:
# 대육별 평균수명과 인구의 총합과 평균
df.groupby('continent')[['lifeExp', 'pop']].agg([np.sum, np.mean])

lifeExp                     pop              
                   sum       mean          sum          mean
continent                                                   
Africa     30491.96600  48.865330   6187585961  9.916003e+06
Americas   19397.62100  64.658737   7351438499  2.450479e+07
Asia       23785.70168  60.064903  30507333901  7.703872e+07
Europe     25885.32700  71.903686   6181115304  1.716976e+07
Oceania     1783.82900  74.326208    212992136  8.874672e+06

In [65]:
# 대륙별 평균수명의 최대값과 최소값 
df.groupby('continent')['lifeExp'].agg([np.min, np.max])

amin    amax
continent                
Africa     23.599  76.442
Americas   37.579  80.653
Asia       28.801  82.603
Europe     43.585  81.757
Oceania    69.120  81.235