- HaarCasCade : openCV에서 제공하는 학습 모델에 적용할 수 있는 가중치가 저장된 파일
- 사전 학습 모델 자체를 제공하는 것이 아닌 모델을 구성하기 위한 값들이 저장되어 있는 파일이다.

In [2]:
import numpy as np
import cv2

In [62]:
# 이미지를 불러온다.
# img = cv2.imread('./opencv_data/image/marathon_01.jpg')
img = cv2.imread('./opencv_data/image/marathon_02.jpg')

In [63]:
# CasCade Classifier 생성
face_cascade = cv2.CascadeClassifier()
eyes_cascade = cv2.CascadeClassifier()

In [64]:
# 가중치 데이터가 들어있는 xml 파일명
face_xml = './opencv_data/haarcascades/haarcascade_frontalface_alt.xml'
eyes_xml = './opencv_data/haarcascades/haarcascade_eye_tree_eyeglasses.xml'

In [65]:
# 가중치 데이터를 학습모델에 적용한다.
face_cascade.load(cv2.samples.findFile(face_xml))
eyes_cascade.load(cv2.samples.findFile(eyes_xml))

True

In [69]:
# 인식률 향상을 이미지 데이터 전처리
# 흑백으로 변환한다.
frame_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# 데이터를 표준화한다.
frame_gray = cv2.equalizeHist(frame_gray)

In [67]:
# 얼굴을 인식한다.
# 결과는 인식된 부분의 이미지상의 좌측 상단 x, y 좌표와 가로, 세로 길이를 가져온다.
faces = face_cascade.detectMultiScale(frame_gray)
faces

array([[ 82,  41, 106, 106]])

In [68]:
# 인식한 얼굴의 수 만큼 반복한다.
for x, y, w, h in faces : 
    # 인식한 얼굴에 네모를 그려준다.
    # 이미지, 좌측상단 x, 좌측상단 y, 우측하단 x, 우측하단 y, 색상, 두께
    frame = cv2.rectangle(img, (x,y), (x+w, y+h), (0, 255, 0), 4)
    
    # 현재의 얼굴 부분만 데이터로 가져온다.
    faceROI = frame_gray[y:y+h, x:x+h]
    # 추출한 얼굴에서 눈을 가져온다.
    eyes = eyes_cascade.detectMultiScale(faceROI)
    print(eyes)
    print('----------------------------------------------------------------------')
    
    # 검출된 눈의 수 만큼 반복한다.
    for x2, y2, w2, h2 in eyes :
        # 눈의 중앙점
        eye_x = x + x2 + w2 // 2
        eye_y = y + y2 + h2 // 2
        # 반경을 게산한다.
        radius = int(round((w2 + h2) * 0.25))
        # 원을 그린다.
        # 그릴 이미지, 원의 중앙점 xy 좌표, 반경, 색상, 두께
        frame = cv2.circle(frame, (eye_x, eye_y), radius, (255, 0, 0), 4)
    
# 이미지를 표시한다.
cv2.imshow('Face Detection', frame)
cv2.waitKey()
cv2.destroyAllWindows()

[[20 31 24 24]
 [64 30 24 24]]
----------------------------------------------------------------------
